(() => {
interface AlertNormalizationSourceAlert { severity?: string; vendor?: string; code?: string; name?: string; recommended_action?: string; probable_cause?: string; device_family?: string; }
interface AlertNormalizationFleetAlert { category?: string; code?: string; name?: string; }
interface AlertNormalizationMapping { mapping_id?: string; source_alert?: AlertNormalizationSourceAlert; zentrid_alert?: AlertNormalizationFleetAlert; ui_fields?: Record<string, string>; }
interface AlertNormalizationCanonical { category?: string; zentrid_alert_code?: string; zentrid_alert_name?: string; ui_binding?: { mapped_vendor_record_count?: number }; }
interface AlertNormalizationDict { vendor_mappings?: AlertNormalizationMapping[]; canonical_alerts?: AlertNormalizationCanonical[]; counts?: { canonical_alerts?: number; vendor_mappings?: number }; }
interface AlertNormalizationState { tab: string; dict: AlertNormalizationDict | null; bindings: unknown; category: string; q: string; }
const PATH_ALERTS = '../assets/data/Zentrid_Canonical_Alerts_UI_Ready_v1.json';
    const PATH_BINDINGS = '../assets/data/Zentrid_UI_Alert_Integration_v1.json';
    const state: AlertNormalizationState = { tab:'mapping', dict:null, bindings:null, category:'All', q:'' };
    function esc(v: unknown): string{const entities: Record<string, string>={'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'};return String(v??'').replace(/[&<>'"]/g,c=>entities[c]??c);}
    function badge(v: unknown): string{const s=String(v||'').toLowerCase();return `<span class="badge ${s.includes('critical')?'danger':s.includes('high')||s.includes('fault')?'warning':'neutral'}">${esc(v||'Info')}</span>`;}
    async function init(): Promise<void>{ const [a,b]=await Promise.all([fetch(PATH_ALERTS,{cache:'no-store'}).then(r=>r.json()), fetch(PATH_BINDINGS,{cache:'no-store'}).then(r=>r.json()).catch((): null => null)]); state.dict=a; state.bindings=b; render(); }
    function mappings(): AlertNormalizationMapping[]{return state.dict?.vendor_mappings||[];}
    function canonical(): AlertNormalizationCanonical[]{return state.dict?.canonical_alerts||[];}
    function categories(): string[]{const values=canonical().map(a=>a.category).filter((category): category is string=>Boolean(category));return ['All', ...new Set(values.sort())];}
    function sev(m: AlertNormalizationMapping): string{const raw=String(m.source_alert?.severity||'').toLowerCase(); if(raw.includes('critical'))return 'Critical'; if(raw.includes('high')||raw.includes('fault'))return 'Fault'; if(raw.includes('medium')||raw.includes('warning'))return 'Warning'; return 'Info';}
    function filtered(): AlertNormalizationMapping[]{const q=state.q.toLowerCase().trim();return mappings().filter(m=>state.category==='All'||m.zentrid_alert?.category===state.category).filter(m=>!q||[m.zentrid_alert?.code,m.zentrid_alert?.name,m.source_alert?.vendor,m.source_alert?.code,m.source_alert?.name].join(' ').toLowerCase().includes(q));}
    function tabs(): string{return `<aside class="glass-card production-side-card-v92"><h3>Alert Normalization</h3>${[['mapping','Vendor Mapping'],['canonical','Canonical Alerts'],['fields','UI Bindings'],['severity','Severity Logic'],['preview','Mapping Preview']].map(([id,label])=>`<button class="${state.tab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}</aside>`;}
    function filters(): string{return `<section class="filter-panel compact-filter-panel"><label>Category<select id="catFilter">${categories().map(c=>`<option ${state.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Search<input id="qFilter" value="${esc(state.q)}" placeholder="Zentrid code, vendor code, vendor name..." /></label><button class="secondary-action" id="resetBtn" type="button">Reset</button></section>`;}
    function mapping(): string{const rows=filtered().slice(0,200);return `<div class="section-title-v17"><div><h2>Vendor Alert Mapping</h2><p class="muted">844 source vendor alerts are mapped into 28 Zentrid canonical alerts. Original vendor code/name/description/action remain separated.</p></div></div>${filters()}<div class="data-table incident-map-table-v94"><div class="data-head incident-map-row-v94"><span>Zentrid Alert</span><span>Vendor Alert</span><span>Category</span><span>Severity</span><span>Vendor Action</span><span>Device Family</span></div>${rows.map(m=>`<div class="data-row incident-map-row-v94"><div><strong>${esc(m.zentrid_alert?.code)}</strong><small>${esc(m.zentrid_alert?.name)}</small></div><div><strong>${esc(m.source_alert?.vendor)} ${esc(m.source_alert?.code)}</strong><small>${esc(m.source_alert?.name)}</small></div><div><strong>${esc(m.zentrid_alert?.category)}</strong><small>${esc(m.mapping_id)}</small></div>${badge(sev(m))}<div><strong>${esc(m.source_alert?.recommended_action).slice(0,90)}</strong><small>${esc(m.source_alert?.probable_cause).slice(0,70)}</small></div><div><strong>${esc(m.source_alert?.device_family).slice(0,45)}</strong><small>source preserved</small></div></div>`).join('')}</div><p class="muted table-note-v95">Showing ${rows.length} of ${filtered().length} filtered mappings.</p>`;}
    function canonicalPanel(): string{return `<div class="section-title-v17"><div><h2>28 Zentrid Canonical Alerts</h2><p class="muted">Controlled alert buckets used by Alert Center, Alert Detail, Notifications and SOP routing.</p></div></div><section class="kpi-grid compact-kpis"><article class="kpi-card cyan"><span>Canonical Alerts</span><strong>${canonical().length}</strong><small>fixed v1 scope</small></article><article class="kpi-card blue"><span>Vendor Mappings</span><strong>${mappings().length}</strong><small>raw vendor rows</small></article><article class="kpi-card green"><span>Categories</span><strong>${categories().length-1}</strong><small>${esc(categories().filter(c=>c!=='All').slice(0,5).join(' · '))}</small></article></section><div class="normalization-empty-grid">${canonical().map(a=>`<article><strong>${esc(a.zentrid_alert_code)}</strong><small>${esc(a.zentrid_alert_name)} · ${esc(a.category)} · ${a.ui_binding?.mapped_vendor_record_count||0} mappings</small></article>`).join('')}</div>`;}
    function fieldsPanel(): string{const sample=mappings()[0]?.ui_fields||{};return `<div class="section-title-v17"><div><h2>Alert UI Bindings</h2><p class="muted">These bindings prevent labels from drifting between Alert List, Alert Detail and Data Governance.</p></div></div><div class="data-table alert-normalization-fields-v4"><div class="data-head"><span>Data Field</span><span>UI Field</span><span>Rule</span></div>${Object.entries(sample).map(([k,v])=>`<div class="data-row"><div><strong>${esc(k)}</strong><small>${k.startsWith('zentrid')?'normalized':'source vendor'}</small></div><div><strong>${esc(v)}</strong><small>UI Dictionary</small></div><div><strong>${k.startsWith('zentrid')?'Display as Zentrid value':'Show as vendor detail only'}</strong><small>no mixed label fields</small></div></div>`).join('')}</div>`;}
    function severityPanel(): string{return `<div class="section-title-v17"><div><h2>Severity Normalization</h2><p class="muted">Vendor severity is preserved, Zentrid severity is derived for UI sorting and workflow priority.</p></div></div><div class="normalization-empty-grid"><article><strong>Critical</strong><small>Arc fault, fire protection, locked battery pack, short circuit and explicit critical vendor severity.</small></article><article><strong>Fault</strong><small>High severity, grid failure, communication loss, overvoltage, hardware fault and active protection states.</small></article><article><strong>Warning</strong><small>Medium severity, configuration review, CT wiring issues and non-blocking abnormal states.</small></article><article><strong>Info</strong><small>Source detail without operational fault impact.</small></article></div>`;}
    function preview(): string{const m=mappings().find(x=>x.zentrid_alert?.code==='FL-COM-RS')||mappings()[0];if(!m)return '<div class="empty-state"><strong>No alert mappings available</strong><small>Load the canonical alert dictionary to preview a mapping.</small></div>';return `<div class="section-title-v17"><div><h2>Mapping Preview</h2><p class="muted">Example of raw vendor alert becoming a Zentrid alert without losing vendor action text.</p></div></div><div class="mapping-preview-card large"><div><small>Vendor Data</small><strong>${esc(m.source_alert?.vendor)} ${esc(m.source_alert?.code)}</strong><em>${esc(m.source_alert?.name)}</em></div><div><small>Mapping</small><strong>${esc(m.source_alert?.vendor)} ${esc(m.source_alert?.code)} → ${esc(m.zentrid_alert?.code)}</strong><em>${esc(m.zentrid_alert?.category)}</em></div><div><small>Zentrid Result</small><strong>${esc(m.zentrid_alert?.name)}</strong><em>${esc(sev(m))} · Vendor action retained</em></div></div><div class="glass-card"><h3>Vendor Recommended Action</h3><p class="muted">${esc(m.source_alert?.recommended_action)}</p></div>`;}
    function active(): string{if(state.tab==='canonical')return canonicalPanel(); if(state.tab==='fields')return fieldsPanel(); if(state.tab==='severity')return severityPanel(); if(state.tab==='preview')return preview(); return mapping();}
    function render(): void{const counts=state.dict?.counts||{};FleetLayout.mount(`<section class="page-hero production-hero"><div><p class="eyebrow">Global Admin · Data Governance</p><h1>Incident Normalization</h1><p class="muted">Vendor alert/error codes normalized to Zentrid canonical alerts using the same normalized registry as Alert Dictionary.</p></div><button class="freshness-card" onclick="FleetLayout.toast('Alert normalization layer loaded')"><span class="pulse"></span><div><strong>${counts.canonical_alerts||28} / ${counts.vendor_mappings||844}</strong><small>canonical alerts / mappings</small></div></button></section><section class="production-workspace-v92">${tabs()}<section class="glass-card production-main-card-v92">${active()}</section></section>`);document.querySelectorAll<HTMLElement>('[data-tab]').forEach((b: HTMLElement)=>{b.onclick=()=>{state.tab=b.dataset.tab || 'mapping';render();};});document.getElementById('catFilter')?.addEventListener('change',(e: Event)=>{state.category=(e.target as HTMLSelectElement).value;render();});document.getElementById('qFilter')?.addEventListener('input',(e: Event)=>{state.q=(e.target as HTMLInputElement).value;setTimeout(render,80);});document.getElementById('resetBtn')?.addEventListener('click',()=>{state.category='All';state.q='';render();});}
    init();
})();
