(() => {
type AgreementTabV58 = 'overview' | 'agreements' | 'templates' | 'terms' | 'scope' | 'documents' | 'renewals' | 'approvals' | 'audit';

interface AgreementRecordV58 {
  id: string;
  name: string;
  type: string;
  client: string;
  tenant: string;
  plants: string;
  value: string;
  cycle: string;
  status: string;
  approval: string;
  renewal: string;
  start: string;
  end: string;
  owner: string;
  documents: string;
  terms: string;
}

interface AgreementTemplateV58 { name: string; type: string; version: string; used: string; status: string; }
interface FinancialTermV58 { name: string; basis: string; value: string; billing: string; status: string; }
interface LinkedScopeV58 { agreement: string; client: string; plants: string; access: string; status: string; }
interface AgreementDocumentV58 { doc: string; agreement: string; type: string; owner: string; status: string; }
interface RenewalQueueItemV58 { agreement: string; client: string; renewal: string; action: string; status: string; }
interface ApprovalQueueItemV58 { item: string; owner: string; step: string; risk: string; status: string; }
interface AgreementAuditItemV58 { time: string; user: string; action: string; entity: string; status: string; }

const agreementRecordsV125: AgreementRecordV58[] = [
      {id:'AGR-2026-041', name:'Arpi Solar Group O&M Agreement', type:'O&M Agreement', client:'Arpi Solar Group', tenant:'Tenant Alpha Energy', plants:'Arpi Plant 01 · Storage Pilot', value:'€4,224 / month', cycle:'Monthly', status:'Active', approval:'Approved', renewal:'12 Dec 2027', start:'12 Dec 2025', end:'12 Dec 2027', owner:'Commercial Admin', documents:'Signed contract · SLA annex · DPA', terms:'Premium SLA, monthly platform and O&M service fee, Net 15 payment terms.'},
      {id:'AGR-2026-055', name:'Ivan Petrov Residential Service Agreement', type:'Service Agreement', client:'Ivan Petrov', tenant:'Tenant North Operations', plants:'Residential PV · Home Battery', value:'€980 / month', cycle:'Monthly', status:'Review', approval:'Finance Review', renewal:'30 Sep 2026', start:'01 Oct 2025', end:'30 Sep 2026', owner:'Finance Admin', documents:'Draft contract · Client ID docs', terms:'Residential monitoring, reports, support plan, Net 30 payment terms.'},
      {id:'AGR-2026-077', name:'Green Valley Direct PPA', type:'Energy Purchase Agreement', client:'Green Valley Estate', tenant:'GridOps Partner', plants:'Green Valley East · Green Valley West', value:'$0.118 / kWh', cycle:'Custom PPA', status:'Active', approval:'Approved', renewal:'18 Jan 2028', start:'18 Jan 2026', end:'18 Jan 2028', owner:'Commercial Admin', documents:'Signed PPA · tariff schedule · settlement appendix', terms:'Direct energy sale, custom settlement schedule, revenue allocation and O&M service scope.'},
      {id:'AGR-2026-089', name:'Solar Partner Revenue Sharing Agreement', type:'Revenue Sharing Agreement', client:'Solar Partner AM', tenant:'Tenant Alpha Energy', plants:'Partner Portfolio AM', value:'8% platform fee', cycle:'Monthly', status:'Draft', approval:'Not submitted', renewal:'—', start:'01 Jul 2026', end:'30 Jun 2028', owner:'Global Admin', documents:'Draft agreement', terms:'Revenue sharing model for tenant-managed energy sale and platform service fee.'}
    ];
    const agreementTemplatesV125: AgreementTemplateV58[] = [
      {name:'O&M Agreement Template', type:'Service', version:'v2.1', used:'12 agreements', status:'Active'},
      {name:'Energy Purchase Agreement Template', type:'Energy Sale', version:'v1.4', used:'5 agreements', status:'Active'},
      {name:'Revenue Sharing Template', type:'Commercial Split', version:'v1.0', used:'2 agreements', status:'Draft'},
      {name:'Subscription Agreement Template', type:'SaaS', version:'v3.2', used:'31 agreements', status:'Active'}
    ];
    const financialTermsV125: FinancialTermV58[] = [
      {name:'Premium O&M Fee', basis:'Monthly fixed fee', value:'€4,224 / month', billing:'Monthly', status:'Active'},
      {name:'Direct PPA Rate', basis:'Exported energy', value:'$0.118 / kWh', billing:'Custom period', status:'Active'},
      {name:'Platform Revenue Share', basis:'Revenue split', value:'8%', billing:'Monthly settlement', status:'Draft'}
    ];
    const linkedScopesV125: LinkedScopeV58[] = [
      {agreement:'AGR-2026-041', client:'Arpi Solar Group', plants:'Arpi Plant 01 · Storage Pilot', access:'Commercial + Billing', status:'Active'},
      {agreement:'AGR-2026-055', client:'Ivan Petrov', plants:'Residential PV · Home Battery', access:'Client Portal + Reports', status:'Review'},
      {agreement:'AGR-2026-077', client:'Green Valley Estate', plants:'Green Valley East · Green Valley West', access:'PPA + Settlement', status:'Active'}
    ];
    const documentsV125: AgreementDocumentV58[] = [
      {doc:'Signed O&M Agreement', agreement:'AGR-2026-041', type:'Contract', owner:'Legal', status:'Signed'},
      {doc:'PPA Tariff Schedule', agreement:'AGR-2026-077', type:'Financial Annex', owner:'Commercial', status:'Signed'},
      {doc:'Revenue Sharing Draft', agreement:'AGR-2026-089', type:'Draft Contract', owner:'Global Admin', status:'Draft'}
    ];
    const renewalQueueV125: RenewalQueueItemV58[] = [
      {agreement:'AGR-2026-055', client:'Ivan Petrov', renewal:'30 Sep 2026', action:'Review terms', status:'Due Soon'},
      {agreement:'AGR-2026-041', client:'Arpi Solar Group', renewal:'12 Dec 2027', action:'Auto-renew enabled', status:'Scheduled'},
      {agreement:'AGR-2026-077', client:'Green Valley Estate', renewal:'18 Jan 2028', action:'PPA schedule check', status:'Scheduled'}
    ];
    const approvalQueueV125: ApprovalQueueItemV58[] = [
      {item:'Revenue Sharing Agreement', owner:'Global Admin', step:'Commercial Review', risk:'High', status:'Pending'},
      {item:'Residential Service Agreement', owner:'Finance Admin', step:'Finance Review', risk:'Medium', status:'Review'},
      {item:'PPA Template v1.4', owner:'Legal', step:'Approved', risk:'High', status:'Approved'}
    ];
    const auditV125: AgreementAuditItemV58[] = [
      {time:'Today · 10:24', user:'Commercial Admin', action:'Agreement opened', entity:'AGR-2026-089', status:'Success'},
      {time:'Today · 09:42', user:'Finance Admin', action:'Financial term updated', entity:'Premium O&M Fee', status:'Success'},
      {time:'Yesterday · 16:10', user:'Legal', action:'Document attached', entity:'PPA Tariff Schedule', status:'Success'}
    ];

    function tone(v: string | number | null | undefined): string{ const s=String(v||'').toLowerCase(); if(s.includes('active')||s.includes('approved')||s.includes('signed')||s.includes('success')||s.includes('scheduled')) return 'success'; if(s.includes('review')||s.includes('pending')||s.includes('due')) return 'warning'; if(s.includes('draft')) return 'neutral'; return 'info'; }
    function badge(v: string): string{ return `<span class="badge ${tone(v)}">${v}</span>`; }
    function action(label: string, fn: string): string{ return `<div class="row-actions kebabified agreement-actions-cell-v125"><button class="small-btn" type="button" onclick="FleetCommercialAgreementsV125.${fn}">${label}</button></div>`; }
    function table(heads: string[], rows: string[], cls = 'agreement-table-v125'): string{ return `<div class="data-table ${cls}"><div class="data-head">${heads.map(h=>`<span>${h}</span>`).join('')}</div>${rows.join('')}</div>`; }
    function openDetail(type: string, title: string, meta: string): void{ const layout = FleetLayout as unknown as FleetLayoutLegacyApi; if(window.FleetLayout && layout.drawer){ layout.drawer(type,{Title:title,Context:meta,Status:'Mock detail'},'<div class="drawer-action-grid"><button>Open Detail</button><button>Edit Draft</button><button>Send for Approval</button><button>View Audit</button></div>'); } }
    function kpis(): string{ return `<div class="module-grid agreement-kpis-v125"><article class="kpi-card"><span>Agreements</span><strong>${agreementRecordsV125.length}</strong><small>Commercial records</small></article><article class="kpi-card"><span>Active</span><strong>${agreementRecordsV125.filter(x=>x.status==='Active').length}</strong><small>Signed / in force</small></article><article class="kpi-card"><span>In Review</span><strong>${agreementRecordsV125.filter(x=>x.status==='Review').length}</strong><small>Needs commercial validation</small></article><article class="kpi-card"><span>Drafts</span><strong>${agreementRecordsV125.filter(x=>x.status==='Draft').length}</strong><small>Not yet approved</small></article></div>`; }
    function flow(): string{ return `<div class="agreement-flow-v125"><article><span>01</span><strong>Client</strong><small>Commercial counterparty</small></article><article><span>02</span><strong>Agreement</strong><small>Contract type and scope</small></article><article><span>03</span><strong>Terms</strong><small>Price, cycle, currency</small></article><article><span>04</span><strong>Billing</strong><small>Invoice generation</small></article><article><span>05</span><strong>Payment</strong><small>Collection and settlement</small></article></div>`; }
    function overview(): string{ return `<div class="section-title-v17 agreement-title-v125"><div><h2>Commercial Agreements Overview</h2><p class="muted">Contracts connect clients, plants, financial terms, billing cycles, documents, renewal and approval logic.</p></div><button class="primary-action" onclick="FleetCommercialAgreementsV125.toast('Agreement draft opened')">Create Agreement</button></div>${kpis()}${flow()}<div class="info-grid agreement-info-grid-v125"><div><span>Default Contract Owner</span><strong>Commercial Admin</strong><small>Responsible for agreement lifecycle.</small></div><div><span>Approval Policy</span><strong>Finance + Legal</strong><small>Required for high-risk agreements.</small></div><div><span>Document Rule</span><strong>Signed version locked</strong><small>Signed contract files are immutable.</small></div><div><span>Payment Link</span><strong>Billing + Payment Center</strong><small>Terms feed invoices and collection.</small></div></div>` + agreements(); }
    function agreements(): string{ return `<div class="section-title-v17 agreement-title-v125"><div><h2>Agreements</h2><p class="muted">Client-level commercial agreements linked to plants, billing and payment configuration.</p></div><button class="secondary-action" onclick="FleetCommercialAgreementsV125.toast('Agreement editor opened')">Add Agreement</button></div>` + table(['Agreement','Client / Tenant','Financial Term','Status','Renewal','Actions'], agreementRecordsV125.map(a=>`<div class="data-row agreement-row-v125"><div><strong>${a.name}</strong><small>${a.id}<br>${a.type}</small></div><div><strong>${a.client}</strong><small>${a.tenant}</small></div><div><strong>${a.value}</strong><small>${a.cycle}</small></div><div>${badge(a.status)}<small>${a.approval}</small></div><div><strong>${a.renewal}</strong><small>${a.owner}</small></div>${action('Open',`open('Agreement','${a.name}','${a.type} · ${a.terms}')`)}</div>`)); }
    function templates(): string{ return `<div class="section-title-v17 agreement-title-v125"><div><h2>Agreement Templates</h2><p class="muted">Reusable contract templates for O&M, PPA, subscription and revenue sharing agreements.</p></div><button class="secondary-action" onclick="FleetCommercialAgreementsV125.toast('Template editor opened')">Add Template</button></div>` + table(['Template','Type','Version','Usage','Status','Actions'], agreementTemplatesV125.map(t=>`<div class="data-row agreement-row-v125"><div><strong>${t.name}</strong><small>Agreement template</small></div><div><strong>${t.type}</strong><small>Template category</small></div><div><strong>${t.version}</strong><small>Current version</small></div><div><strong>${t.used}</strong><small>Linked agreements</small></div><div>${badge(t.status)}</div>${action('Open',`open('Agreement Template','${t.name}','${t.type} · ${t.version}')`)}</div>`)); }
    function financialTerms(): string{ return `<div class="section-title-v17 agreement-title-v125"><div><h2>Financial Terms</h2><p class="muted">Pricing, billing cycle and financial terms that feed Billing Center and Payment Center.</p></div><button class="secondary-action" onclick="FleetCommercialAgreementsV125.toast('Financial term editor opened')">Add Term</button></div>` + table(['Term','Basis','Value','Billing','Status','Actions'], financialTermsV125.map(t=>`<div class="data-row agreement-row-v125"><div><strong>${t.name}</strong><small>Financial term</small></div><div><strong>${t.basis}</strong><small>Calculation basis</small></div><div><strong>${t.value}</strong><small>Price / rate</small></div><div><strong>${t.billing}</strong><small>Billing cycle</small></div><div>${badge(t.status)}</div>${action('Open',`open('Financial Term','${t.name}','${t.value} · ${t.billing}')`)}</div>`)) + `<div class="section-title-v17 mini agreement-title-v125"><div><h3>Term Controls</h3><p class="muted">Rules applied before invoices are generated.</p></div></div><div class="info-grid agreement-info-grid-v125"><div><span>Currency</span><strong>Agreement controlled</strong><small>Currency comes from each contract.</small></div><div><span>Tax Handling</span><strong>Billing Center</strong><small>Applied during invoice draft creation.</small></div><div><span>Discounts</span><strong>Allowed</strong><small>Requires approval when above threshold.</small></div><div><span>Versioning</span><strong>Enabled</strong><small>Old financial terms remain auditable.</small></div></div>`; }
    function linkedScope(): string{ return `<div class="section-title-v17 agreement-title-v125"><div><h2>Linked Clients & Plants</h2><p class="muted">Shows which client and plant scope each agreement controls.</p></div></div>` + table(['Agreement','Client','Plants','Access Scope','Status','Actions'], linkedScopesV125.map(s=>`<div class="data-row agreement-row-v125"><div><strong>${s.agreement}</strong><small>Agreement reference</small></div><div><strong>${s.client}</strong><small>Commercial counterparty</small></div><div><small>${s.plants}</small></div><div><strong>${s.access}</strong><small>Scope type</small></div><div>${badge(s.status)}</div>${action('Open',`open('Linked Scope','${s.agreement}','${s.client} · ${s.plants}')`)}</div>`)); }
    function documents(): string{ return `<div class="section-title-v17 agreement-title-v125"><div><h2>Documents</h2><p class="muted">Contract documents, financial annexes and signed files connected to agreements.</p></div><button class="secondary-action" onclick="FleetCommercialAgreementsV125.toast('Document upload opened')">Upload Document</button></div>` + table(['Document','Agreement','Type','Owner','Status','Actions'], documentsV125.map(d=>`<div class="data-row agreement-row-v125"><div><strong>${d.doc}</strong><small>Agreement document</small></div><div><strong>${d.agreement}</strong><small>Reference</small></div><div><strong>${d.type}</strong><small>Document type</small></div><div><strong>${d.owner}</strong><small>Document owner</small></div><div>${badge(d.status)}</div>${action('Open',`open('Agreement Document','${d.doc}','${d.type} · ${d.status}')`)}</div>`)); }
    function renewals(): string{ return `<div class="section-title-v17 agreement-title-v125"><div><h2>Renewals</h2><p class="muted">Upcoming renewal dates, contract checks and commercial actions.</p></div><button class="secondary-action" onclick="FleetCommercialAgreementsV125.toast('Renewal rule editor opened')">Add Renewal Rule</button></div>` + table(['Agreement','Client','Renewal Date','Action','Status','Actions'], renewalQueueV125.map(r=>`<div class="data-row agreement-row-v125"><div><strong>${r.agreement}</strong><small>Agreement</small></div><div><strong>${r.client}</strong><small>Client</small></div><div><strong>${r.renewal}</strong><small>Renewal date</small></div><div><strong>${r.action}</strong><small>Next step</small></div><div>${badge(r.status)}</div>${action('Open',`open('Renewal','${r.agreement}','${r.client} · ${r.renewal}')`)}</div>`)); }
    function approvals(): string{ return `<div class="section-title-v17 agreement-title-v125"><div><h2>Approval Workflow</h2><p class="muted">Approval controls for new agreements, financial changes and high-risk contract actions.</p></div><button class="secondary-action" onclick="FleetCommercialAgreementsV125.toast('Approval workflow editor opened')">Add Workflow</button></div>` + table(['Item','Owner','Step','Risk','Status','Actions'], approvalQueueV125.map(a=>`<div class="data-row agreement-row-v125"><div><strong>${a.item}</strong><small>Approval item</small></div><div><strong>${a.owner}</strong><small>Responsible</small></div><div><strong>${a.step}</strong><small>Current step</small></div><div>${badge(a.risk)}</div><div>${badge(a.status)}</div>${action('Open',`open('Approval Item','${a.item}','${a.step} · ${a.risk}')`)}</div>`)) + `<div class="agreement-approval-flow-v125"><article><span>Step 1</span><strong>Commercial Review</strong><small>Scope, pricing and linked devices.</small></article><article><span>Step 2</span><strong>Finance Review</strong><small>Billing, payment terms and settlement impact.</small></article><article><span>Step 3</span><strong>Legal Approval</strong><small>Contract documents and signed versions.</small></article></div>`; }
    function audit(): string{ return `<div class="section-title-v17 agreement-title-v125"><div><h2>Audit Log</h2><p class="muted">Immutable agreement lifecycle trace.</p></div><button class="secondary-action" onclick="FleetCommercialAgreementsV125.toast('Agreement audit export prepared')">Export Audit</button></div>` + table(['Timestamp','User','Action','Entity','Status','Actions'], auditV125.map(a=>`<div class="data-row agreement-row-v125"><div><strong>${a.time}</strong><small>Timestamp</small></div><div><strong>${a.user}</strong><small>Actor</small></div><div><strong>${a.action}</strong><small>Change</small></div><div><strong>${a.entity}</strong><small>Entity</small></div><div>${badge(a.status)}</div>${action('Open',`open('Audit Record','${a.action}','${a.entity}')`)}</div>`)); }
    function content(tab: string | undefined): string{ return tab==='agreements'?agreements():tab==='templates'?templates():tab==='terms'?financialTerms():tab==='scope'?linkedScope():tab==='documents'?documents():tab==='renewals'?renewals():tab==='approvals'?approvals():tab==='audit'?audit():overview(); }
    window.FleetCommercialAgreementsV125 = { toast(msg: string): void{ if(window.FleetLayout && FleetLayout.toast) FleetLayout.toast(msg); else alert(msg); }, open(type: string, title: string, meta: string): void{ openDetail(type,title,meta); } };
    FleetLayout.mount(`<section class="page-hero"><div><p class="eyebrow">Global Admin · Financial Operations</p><h1>Commercial Agreements</h1><p class="muted">Agreement workspace for contracts, templates, financial terms, linked clients and plants, documents, renewals, approvals and audit.</p></div><button class="secondary-action" onclick="location.href='commercial-models.html'">Back to Commercial Models</button></section><section class="plant-workspace-v17 agreement-workspace-v125"><aside class="glass-card plant-side-card-v17 agreement-side-v125"><h3>Agreement Workspace</h3><button class="active" data-agreement-tab="overview">Overview</button><button data-agreement-tab="agreements">Agreements</button><button data-agreement-tab="templates">Agreement Templates</button><button data-agreement-tab="terms">Financial Terms</button><button data-agreement-tab="scope">Linked Clients & Plants</button><button data-agreement-tab="documents">Documents</button><button data-agreement-tab="renewals">Renewals</button><button data-agreement-tab="approvals">Approval Workflow</button><button data-agreement-tab="audit">Audit Log</button></aside><section class="glass-card plant-main-card-v17 agreement-main-card-v125" id="agreementContent">${content('overview')}</section></section>`);
    document.addEventListener('click', (e: MouseEvent)=>{ const target = e.target as Element | null; const b = target?.closest('[data-agreement-tab]') as HTMLElement | null; if(!b) return; document.querySelectorAll('[data-agreement-tab]').forEach((x: Element)=>x.classList.toggle('active',x===b)); const contentNode = document.getElementById('agreementContent'); if(contentNode) contentNode.innerHTML=content(b.dataset.agreementTab); });

})();
