const PaymentSettings = (() => {
      const state = {
        activeTab: 'overview',
        invoiceFlow: [
          { step: '01', label: 'Invoice Sent', detail: 'Approved invoice delivered to billing contact', status: 'Done' },
          { step: '02', label: 'Payment Initiated', detail: 'Bank transfer, card, direct debit or deposit balance', status: 'Done' },
          { step: '03', label: 'Payment Processing', detail: 'Gateway, bank or ERP source confirms transaction', status: 'Processing' },
          { step: '04', label: 'Payment Confirmed', detail: 'Payment status moves to captured or paid', status: 'Pending' },
          { step: '05', label: 'Payment Allocated', detail: 'Fees, penalties, invoices or deposit balance', status: 'Pending' },
          { step: '06', label: 'ERP Synced', detail: 'Payment, allocation and audit event exported', status: 'Pending' }
        ],
        methods: [
          { code: 'BANK_TRANSFER', name: 'Bank Transfer', type: 'bank_transfer', currencies: 'EUR, USD, AMD', countries: 'AM, EU', min: 10, max: 500000, fee: '0.00% + 0.00', settlement: '1-2 business days', reconcile: 'Yes', status: 'Active' },
          { code: 'CARD_STRIPE', name: 'Card Payment · Stripe', type: 'card_gateway', currencies: 'EUR, USD', countries: 'Global', min: 1, max: 10000, fee: '2.90% + 0.30', settlement: 'T+2', reconcile: 'Yes', status: 'Active' },
          { code: 'SEPA_DIRECT', name: 'SEPA Direct Debit', type: 'direct_debit', currencies: 'EUR', countries: 'EU', min: 5, max: 25000, fee: '0.35% + 0.00', settlement: 'T+3', reconcile: 'Yes', status: 'Review' },
          { code: 'CLIENT_DEPOSIT', name: 'Client Deposit Balance', type: 'internal_balance', currencies: 'EUR, USD, AMD', countries: 'All', min: 0, max: 999999, fee: '0.00% + 0.00', settlement: 'Immediate', reconcile: 'Auto', status: 'Active' }
        ],
        gateways: [
          { provider: 'Stripe', code: 'stripe', mode: 'Production', merchant: 'zentrid_global', currencies: 'EUR, USD', countries: 'Global', fee: '2.90% + 0.30', refund: 'Yes', chargeback: 'Yes', payout: 'Daily', status: 'Active', webhookSignature: 'Enabled', keysEncrypted: 'Yes', ipWhitelist: 'Enabled', apiKey: 'Encrypted', secretKey: 'Encrypted' },
          { provider: 'Adyen', code: 'adyen', mode: 'Test', merchant: 'adyen_demo_zentrid', currencies: 'EUR, USD, GBP', countries: 'EU, UK, US', fee: '2.70% + 0.25', refund: 'Yes', chargeback: 'Yes', payout: 'Weekly', status: 'Review', webhookSignature: 'Enabled', keysEncrypted: 'Yes', ipWhitelist: 'Review', apiKey: 'Encrypted', secretKey: 'Encrypted' },
          { provider: 'Ameriabank', code: 'ameriabank', mode: 'Production', merchant: 'zentrid_am', currencies: 'AMD, USD, EUR', countries: 'AM', fee: '1.80%', refund: 'Manual', chargeback: 'No', payout: 'T+1', status: 'Active', webhookSignature: 'Enabled', keysEncrypted: 'Yes', ipWhitelist: 'Enabled', apiKey: 'Encrypted', secretKey: 'Encrypted' }
        ],
        banks: [
          { entity: 'Zentrid Global Ltd', bank: 'ACBA Bank', account: 'AM00 0000 0000 0000 0000', swift: 'AGCAAM22', currency: 'AMD', country: 'Armenia', beneficiary: 'Zentrid Global Ltd', correspondent: '—', purpose: 'Invoice {{invoice_no}} · {{customer}}', status: 'Active' },
          { entity: 'Zentrid Global Ltd', bank: 'Ameriabank', account: 'AM99 1111 2222 3333 4444', swift: 'ARMIAM22', currency: 'EUR', country: 'Armenia', beneficiary: 'Zentrid Global Ltd', correspondent: 'Commerzbank DE', purpose: 'Invoice {{invoice_no}}', status: 'Active' },
          { entity: 'Zentrid Europe BV', bank: 'ING Bank', account: 'NL00 INGB 0000 0000 00', swift: 'INGBNL2A', currency: 'EUR', country: 'Netherlands', beneficiary: 'Zentrid Europe BV', correspondent: '—', purpose: 'Zentrid subscription {{invoice_no}}', status: 'Draft' }
        ],
        terms: [
          { code: 'NET_7', name: 'Net 7', due: 7, grace: 3, penalty: '0.05% / day', frequency: 'Daily', reminders: 'Enabled', suspension: 'Day 30' },
          { code: 'NET_15', name: 'Net 15', due: 15, grace: 5, penalty: '0.05% / day', frequency: 'Daily', reminders: 'Enabled', suspension: 'Day 45' },
          { code: 'NET_30', name: 'Net 30', due: 30, grace: 7, penalty: '0.03% / day', frequency: 'Daily', reminders: 'Enabled', suspension: 'Day 60' },
          { code: 'PREPAID', name: 'Prepaid', due: 0, grace: 0, penalty: 'None', frequency: 'None', reminders: 'Disabled', suspension: 'Immediate if unpaid' }
        ],
        profiles: [
          { customer: 'ArSun Energy LLC', method: 'Bank Transfer', currency: 'EUR', email: 'billing@arsun.example', tax: 'VAT-AM-10291', term: 'Net 15', credit: '€35,000', deposit: '€4,500', auto: 'No', format: 'PDF + XLSX', contact: 'Ani Petrosyan' },
          { customer: 'Caucasus Solar O&M', method: 'Card Payment · Stripe', currency: 'EUR', email: 'finance@cso.example', tax: 'VAT-EU-4421', term: 'Net 30', credit: '€120,000', deposit: '€0', auto: 'Yes', format: 'PDF', contact: 'Mikael Brown' },
          { customer: 'Demo Industrial Plant', method: 'Client Deposit Balance', currency: 'AMD', email: 'accounts@demo.example', tax: 'TIN-00918', term: 'Prepaid', credit: '֏0', deposit: '֏1,200,000', auto: 'Yes', format: 'PDF', contact: 'Narek Sargsyan' }
        ],
        fees: [
          { fee: 'Card processing fee', handling: 'Charged to customer', model: 'Percent + fixed', value: '2.90% + 0.30 EUR', applies: 'Card payments', status: 'Active' },
          { fee: 'SWIFT bank fee', handling: 'Split between parties', model: 'Fixed', value: '25 EUR', applies: 'SWIFT transfers', status: 'Active' },
          { fee: 'FX margin', handling: 'Charged to customer', model: 'Percent', value: '1.50%', applies: 'Cross-currency payments', status: 'Active' },
          { fee: 'Chargeback fee', handling: 'Charged to customer', model: 'Fixed', value: '30 EUR', applies: 'Card disputes', status: 'Review' }
        ],
        reconciliation: [
          { source: 'Bank statement · ACBA', matches: 42, exact: 37, probable: 4, unmatched: 1, lastRun: '22 Jun 2026 09:40', status: 'Matched' },
          { source: 'Stripe settlement report', matches: 88, exact: 82, probable: 5, unmatched: 1, lastRun: '22 Jun 2026 08:20', status: 'Matched' },
          { source: 'ERP payment import', matches: 19, exact: 14, probable: 3, unmatched: 2, lastRun: '21 Jun 2026 18:10', status: 'Review' }
        ],
        reconciliationExceptions: [
          { id: 'REC-901', source: 'Bank statement · ACBA', reference: 'INV-2026-0618', customer: 'Demo Industrial Plant', amount: '€600.00', currency: 'EUR', match: 'Probable', issue: 'Sender name mismatch', action: 'Review' },
          { id: 'REC-902', source: 'Stripe settlement report', reference: 'PAY-9921', customer: 'ArSun Energy LLC', amount: '€450.00', currency: 'EUR', match: 'Partial', issue: 'Amount differs by bank fee', action: 'Review' },
          { id: 'REC-903', source: 'ERP payment import', reference: 'UNKNOWN-224', customer: 'Unresolved', amount: '€1,250.00', currency: 'EUR', match: 'Unmatched', issue: 'No invoice reference found', action: 'Manual Match' }
        ],
        refunds: [
          { id: 'RF-1042', customer: 'ArSun Energy LLC', payment: 'PAY-9921', amount: '€450.00', reason: 'Overpayment', approval: 'Auto allowed', destination: 'Original bank account', status: 'Requested' },
          { id: 'RF-1041', customer: 'Caucasus Solar O&M', payment: 'PAY-9897', amount: '€1,250.00', reason: 'Service credit', approval: 'Finance Manager', destination: 'Client deposit', status: 'Approved' },
          { id: 'CB-203', customer: 'Demo Industrial Plant', payment: 'PAY-9822', amount: '€600.00', reason: 'Card dispute', approval: 'Evidence required', destination: 'Gateway dispute', status: 'Disputed' }
        ],
        payouts: [
          { recipient: 'Vendor · SolarParts EU', schedule: 'Weekly', minimum: '€500', currency: 'EUR', bank: 'ING EUR Account', commission: '5%', withholding: '0%', approval: 'Auto below €10k', status: 'Ready' },
          { recipient: 'Operator · Caucasus Solar O&M', schedule: 'Monthly', minimum: '€1,000', currency: 'EUR', bank: 'Ameriabank EUR', commission: '12%', withholding: '5%', approval: 'Finance approval', status: 'Pending' },
          { recipient: 'Energy Trader · GridFlow', schedule: 'Daily', minimum: '€250', currency: 'EUR', bank: 'SEPA payout account', commission: '2%', withholding: '0%', approval: 'Auto', status: 'Ready' }
        ],
        autoPayRules: [
          { name: 'Standard subscription auto-charge', scope: 'Monthly subscription', enabled: 'Enabled', method: 'Card Payment · Stripe', max: '€1,000', retry: '3 attempts', interval: '24h', fallback: 'Bank Transfer', failure: 'Email + In-App' },
          { name: 'Marketplace commission auto-charge', scope: 'Marketplace fees', enabled: 'Review', method: 'SEPA Direct Debit', max: '€5,000', retry: '2 attempts', interval: '48h', fallback: 'Manual approval', failure: 'Finance escalation' },
          { name: 'Premium modules auto-charge', scope: 'AI / BESS / Trading modules', enabled: 'Enabled', method: 'Client Deposit Balance', max: '€2,500', retry: '1 attempt', interval: '12h', fallback: 'Card Payment · Stripe', failure: 'Webhook + Email' }
        ],
        allocations: [
          { priority: 1, bucket: 'Bank Fees', rule: 'Deduct payment processing and transfer fees first', target: 'Payment fee ledger', status: 'Active' },
          { priority: 2, bucket: 'Penalties', rule: 'Apply late fees and penalty charges before principal invoices', target: 'Overdue penalty lines', status: 'Active' },
          { priority: 3, bucket: 'Oldest Overdue Invoices', rule: 'Close the oldest overdue invoice balance first', target: 'A/R oldest balance', status: 'Active' },
          { priority: 4, bucket: 'Current Invoices', rule: 'Allocate remaining amount to current open invoices', target: 'Current receivables', status: 'Active' },
          { priority: 5, bucket: 'Deposit Balance', rule: 'Store unallocated remaining balance as customer deposit', target: 'Customer deposit account', status: 'Active' }
        ],
        disputes: [
          { id: 'DSP-3201', invoice: 'INV-2026-0618', customer: 'Demo Industrial Plant', amount: '€600.00', reason: 'Cardholder dispute', deadline: '28 Jun 2026', evidence: 'Required', status: 'Evidence Required' },
          { id: 'DSP-3199', invoice: 'INV-2026-0598', customer: 'Caucasus Solar O&M', amount: '€1,250.00', reason: 'Service credit disagreement', deadline: '30 Jun 2026', evidence: 'Uploaded', status: 'Under Review' },
          { id: 'DSP-3194', invoice: 'INV-2026-0571', customer: 'ArSun Energy LLC', amount: '€450.00', reason: 'Duplicate transfer claim', deadline: '24 Jun 2026', evidence: 'Complete', status: 'Ready to Resolve' }
        ],
        notifications: [
          { event: 'Invoice Sent', channels: 'Email · In-App', recipients: 'Billing contact + owner admin', template: 'invoice_sent_v2', status: 'Active' },
          { event: 'Payment Received', channels: 'Email · Webhook · ERP', recipients: 'Finance + customer billing', template: 'payment_received_v1', status: 'Active' },
          { event: 'Payment Failed', channels: 'Email · SMS · In-App', recipients: 'Billing contact + finance admin', template: 'payment_failed_v1', status: 'Active' },
          { event: 'Overdue Invoice', channels: 'Email · In-App', recipients: 'Customer admin + collections', template: 'invoice_overdue_v3', status: 'Active' },
          { event: 'Refund Completed', channels: 'Email · Webhook', recipients: 'Billing contact + finance', template: 'refund_completed_v1', status: 'Active' },
          { event: 'Chargeback Received', channels: 'Email · In-App · SMS', recipients: 'Finance manager + security', template: 'chargeback_received_v1', status: 'Review' },
          { event: 'Auto-Payment Failed', channels: 'Email · In-App · Webhook', recipients: 'Billing contact + finance admin', template: 'auto_payment_failed_v2', status: 'Active' }
        ],
        audit: [
          { action: 'Payment gateway updated', entity: 'Stripe', old: 'mode=test', next: 'mode=production', by: 'Global Admin', at: '22 Jun 2026 10:12' },
          { action: 'Bank account created', entity: 'ING EUR Account', old: '—', next: 'status=draft', by: 'Finance Admin', at: '21 Jun 2026 17:41' },
          { action: 'Payment term changed', entity: 'NET_15', old: 'grace=3', next: 'grace=5', by: 'Global Admin', at: '20 Jun 2026 12:26' },
          { action: 'Refund approved', entity: 'RF-1041', old: 'requested', next: 'approved', by: 'Finance Manager', at: '19 Jun 2026 15:09' }
        ]
      };

      function tone(value: unknown): string {
        const v = String(value || '').toLowerCase();
        if (v.includes('active') || v.includes('yes') || v.includes('matched') || v.includes('ready') || v.includes('approved') || v.includes('paid') || v.includes('auto')) return 'success';
        if (v.includes('review') || v.includes('pending') || v.includes('requested') || v.includes('draft') || v.includes('probable')) return 'warning';
        if (v.includes('failed') || v.includes('disputed') || v.includes('no') || v.includes('chargeback')) return 'danger';
        return 'info';
      }
      function money(n: number, currency = 'EUR'): string {
        return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(n);
      }
      function rowCells(values: Array<[string | number, (string | number)?]>): string { return values.map(v => `<div><strong>${v[0]}</strong><small>${v[1] || ''}</small></div>`).join(''); }
      function table(heads: string[], rows: string[], cls = ''): string {
        return `<div class="data-table payment-table ${cls}"><div class="data-head">${heads.map(h => `<span>${h}</span>`).join('')}</div>${rows.join('')}</div>`;
      }
      function actionButton(label: string, handler: string, cls = 'secondary-action'): string {
        return `<button class="${cls}" type="button" onclick="${handler}">${label}</button>`;
      }
      function openModal(title: string, body: string, footer: string): void {
        closeModal();
        const modal = document.createElement('div');
        modal.className = 'commercial-modal-backdrop';
        modal.id = 'paymentSettingsModal';
        modal.innerHTML = `<div class="commercial-modal payment-modal"><div class="commercial-modal-head"><div><h2>${title}</h2><p class="muted">Payment Settings configuration</p></div><button type="button" class="icon-action" onclick="PaymentSettings.closeModal()">×</button></div><div class="commercial-modal-body">${body}</div><div class="commercial-modal-footer">${footer}</div></div>`;
        document.body.appendChild(modal);
      }
      function closeModal() { document.getElementById('paymentSettingsModal')?.remove(); }
      function input(label: string, id: string, value: string | number = '', type: string = 'text') { return `<label>${label}<input id="${id}" type="${type}" value="${value}"></label>`; }
      function select(label: string, id: string, values: string[], selected: string = values[0] ?? '') { return `<label>${label}<select id="${id}">${values.map(v => `<option ${v === selected ? 'selected' : ''}>${v}</option>`).join('')}</select></label>`; }

      function kpis(): string {
        const activeMethods = state.methods.filter(m => m.status === 'Active').length;
        const activeGateways = state.gateways.filter(g => g.status === 'Active').length;
        const unmatched = state.reconciliation.reduce((s, r) => s + r.unmatched, 0);
        const requestedRefunds = state.refunds.filter(r => r.status === 'Requested' || r.status === 'Disputed').length;
        return `<section class="module-grid payment-kpi-grid">
          <article class="module-card"><span>Active Methods</span><strong>${activeMethods}</strong><small>${state.methods.length} configured methods</small></article>
          <article class="module-card"><span>Active Gateways</span><strong>${activeGateways}</strong><small>Production payment providers</small></article>
          <article class="module-card"><span>Unmatched Payments</span><strong>${unmatched}</strong><small>Need reconciliation review</small></article>
          <article class="module-card"><span>Refund / Dispute Queue</span><strong>${requestedRefunds}</strong><small>Require finance action</small></article>
        </section>`;
      }
      function invoicePaymentFlow(): string {
        return `<div class="commercial-governance-flow-v99 payment-flow payment-invoice-flow">${state.invoiceFlow.map(f => `<article class="${tone(f.status)}"><span>${f.step}</span><strong>${f.label}</strong><small>${f.detail}</small><em>${f.status}</em></article>`).join('')}</div>`;
      }
      function overview(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Payment Settings Overview</h2><p>Payment Settings controls how invoices are paid, matched, allocated, refunded, settled and audited. It does not calculate invoice value; it manages the payment lifecycle after invoice generation.</p></div><div class="payment-actions">${actionButton('Advance Payment Flow', 'PaymentSettings.advancePaymentFlow()', 'primary-action')}${actionButton('Run Reconciliation', 'PaymentSettings.runReconciliation()')}${actionButton('Export Settings', 'PaymentSettings.exportSettings()')}</div></div>${kpis()}${invoicePaymentFlow()}</section>${methods()}`;
      }
      function methods(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Payment Methods</h2><p>Bank transfer, cards, direct debit, SWIFT, SEPA, PayPal, Stripe, Adyen, local providers and internal client deposit balance.</p></div><div class="payment-actions">${actionButton('+ Add Method', 'PaymentSettings.openMethodModal()', 'primary-action')}</div></div>${table(['Method', 'Type', 'Currencies', 'Limits', 'Fee', 'Reconciliation', 'Status', 'Actions'], state.methods.map((m, i) => `<div class="data-row payment-method-row"><div><strong>${m.name}</strong><small>${m.code}</small></div><div><strong>${m.type}</strong><small>${m.countries}</small></div><div><strong>${m.currencies}</strong><small>${m.settlement}</small></div><div><strong>${m.min} → ${m.max}</strong><small>Min / max amount</small></div><div><strong>${m.fee}</strong><small>Processing fee</small></div><span class="badge ${tone(m.reconcile)}">${m.reconcile}</span><span class="badge ${tone(m.status)}">${m.status}</span><div class="payment-row-actions"><button type="button" onclick="PaymentSettings.toggleMethod(${i})">${m.status === 'Active' ? 'Disable' : 'Activate'}</button><button type="button" onclick="PaymentSettings.openMethodModal(${i})">Edit</button></div></div>`), 'payment-method-table')}`;
      }
      function gatewaySecurityDetails(): string {
        return table(['Gateway', 'API Keys', 'Secret Key', 'Webhook Signature', 'IP Whitelist', 'Mode'], state.gateways.map((g, i) => `<div class="data-row payment-gateway-security-row"><div><strong>${g.provider}</strong><small>${g.code}</small></div><span class="badge ${tone(g.keysEncrypted)}">${g.apiKey || 'Encrypted'}</span><span class="badge ${tone(g.keysEncrypted)}">${g.secretKey || 'Encrypted'}</span><span class="badge ${tone(g.webhookSignature)}">${g.webhookSignature || 'Enabled'}</span><span class="badge ${tone(g.ipWhitelist)}">${g.ipWhitelist || 'Enabled'}</span><div class="payment-row-actions"><button type="button" onclick="PaymentSettings.toggleGatewayMode(${i})">${g.mode}</button><button type="button" onclick="PaymentSettings.rotateGatewayKeys(${i})">Rotate Keys</button></div></div>`), 'payment-gateway-security-table');
      }
      function gateways(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Payment Gateway Configuration</h2><p>Provider code, encrypted API credentials, merchant ID, webhook URL, callback URL, supported currencies and production/test mode.</p></div><div class="payment-actions">${actionButton('+ Add Gateway', 'PaymentSettings.openGatewayModal()', 'primary-action')}${actionButton('Test Webhooks', 'PaymentSettings.testWebhooks()')}${actionButton('Verify Security', 'PaymentSettings.verifySecurity()')}</div></div>${table(['Gateway', 'Mode', 'Merchant', 'Coverage', 'Fees', 'Refunds', 'Payout', 'Status'], state.gateways.map(g => `<div class="data-row payment-gateway-row"><div><strong>${g.provider}</strong><small>${g.code}</small></div><div><strong>${g.mode}</strong><small>Environment</small></div><div><strong>${g.merchant}</strong><small>API keys encrypted</small></div><div><strong>${g.currencies}</strong><small>${g.countries}</small></div><div><strong>${g.fee}</strong><small>Transaction fee</small></div><span class="badge ${tone(g.refund)}">Refund: ${g.refund}</span><div><strong>${g.payout}</strong><small>Schedule</small></div><span class="badge ${tone(g.status)}">${g.status}</span></div>`), 'payment-gateway-table')}<div class="payment-subsection"><h3>Gateway Security Details</h3><p class="muted">Required controls from Payment Settings: encrypted keys, webhook signature verification, IP whitelist and environment mode.</p>${gatewaySecurityDetails()}</div></section>`;
      }
      function banks(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Bank Account Settings</h2><p>Platform bank accounts by legal entity and currency. Multi-currency setups usually require separate EUR, USD, AMD and GBP accounts.</p></div><div class="payment-actions">${actionButton('+ Add Bank Account', 'PaymentSettings.openBankModal()', 'primary-action')}</div></div>${table(['Legal Entity', 'Bank', 'Account / IBAN', 'SWIFT', 'Currency', 'Beneficiary', 'Purpose', 'Status'], state.banks.map(b => `<div class="data-row payment-bank-row"><div><strong>${b.entity}</strong><small>${b.country}</small></div><div><strong>${b.bank}</strong><small>${b.correspondent}</small></div><div><strong>${b.account}</strong><small>Account number / IBAN</small></div><div><strong>${b.swift}</strong><small>SWIFT / BIC</small></div><div><strong>${b.currency}</strong><small>Currency</small></div><div><strong>${b.beneficiary}</strong><small>Beneficiary</small></div><div><strong>${b.purpose}</strong><small>Payment purpose template</small></div><span class="badge ${tone(b.status)}">${b.status}</span></div>`), 'payment-bank-table')}`;
      }
      function terms(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Payment Terms</h2><p>Due days, grace period, late payment fee, penalty frequency, auto-reminders and service suspension rules.</p></div><div class="payment-actions">${actionButton('+ Add Payment Term', 'PaymentSettings.openTermModal()', 'primary-action')}</div></div>${table(['Code', 'Name', 'Due Days', 'Grace', 'Penalty', 'Frequency', 'Reminders', 'Suspension'], state.terms.map(t => `<div class="data-row payment-terms-row"><div><strong>${t.code}</strong><small>Term code</small></div><div><strong>${t.name}</strong><small>Payment term</small></div><div><strong>${t.due}</strong><small>Due days</small></div><div><strong>${t.grace}</strong><small>Grace period</small></div><div><strong>${t.penalty}</strong><small>Late fee</small></div><div><strong>${t.frequency}</strong><small>Calculation frequency</small></div><span class="badge ${tone(t.reminders)}">${t.reminders}</span><div><strong>${t.suspension}</strong><small>Service rule</small></div></div>`), 'payment-terms-table')}`;
      }
      function profiles(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Customer Payment Profiles</h2><p>Default method, billing currency, billing email, tax number, payment term, credit limit, deposit balance and auto-payment preference.</p></div><div class="payment-actions">${actionButton('+ Add Profile', 'PaymentSettings.openProfileModal()', 'primary-action')}${actionButton('Test Payment Route', 'PaymentSettings.testPaymentRoute()')}</div></div>${table(['Customer', 'Default Method', 'Currency', 'Billing Contact', 'Tax / Term', 'Credit / Deposit', 'Auto', 'Format', 'Actions'], state.profiles.map((p, i) => `<div class="data-row payment-profile-row"><div><strong>${p.customer}</strong><small>${p.contact}</small></div><div><strong>${p.method}</strong><small>Default payment method</small></div><div><strong>${p.currency}</strong><small>Billing currency</small></div><div><strong>${p.email}</strong><small>Payment contact</small></div><div><strong>${p.tax}</strong><small>${p.term}</small></div><div><strong>${p.credit}</strong><small>Deposit ${p.deposit}</small></div><span class="badge ${tone(p.auto)}">Auto: ${p.auto}</span><div><strong>${p.format}</strong><small>Invoice format</small></div><div class="payment-row-actions"><button type="button" onclick="PaymentSettings.openProfileModal(${i})">Edit</button><button type="button" onclick="PaymentSettings.resetProfile(${i})">Reset</button></div></div>`), 'payment-profile-table')}`;
      }
      function autopayFxFees(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Auto-Payment, Currency & Fees</h2><p>Auto-charge rules, retry policy, fallback method, FX settings, rounding rules and payment fee handling.</p></div><div class="payment-actions">${actionButton('+ Create Rule', 'PaymentSettings.openAutoPayRuleModal()', 'primary-action')}${actionButton('Test Rule', 'PaymentSettings.testAutoPayRule()')}${actionButton('Refresh FX', 'PaymentSettings.refreshFx()')}</div></div><div class="info-grid payment-info-grid"><div><span>Base Currency</span><strong>EUR</strong><small>Platform base currency</small></div><div><span>FX Provider</span><strong>Central Bank / Manual</strong><small>Rate date = payment date</small></div><div><span>FX Margin</span><strong>1.5%</strong><small>Configurable per currency</small></div><div><span>Rounding</span><strong>EUR/USD 0.01 · AMD 1</strong><small>Final-stage rounding</small></div></div>${table(['Rule', 'Scope', 'Enabled', 'Method', 'Max Amount', 'Retry', 'Fallback', 'Notification', 'Actions'], state.autoPayRules.map((r, i) => `<div class="data-row payment-autopay-row"><div><strong>${r.name}</strong><small>Auto-payment rule</small></div><div><strong>${r.scope}</strong><small>Applies to</small></div><span class="badge ${tone(r.enabled)}">${r.enabled}</span><div><strong>${r.method}</strong><small>Primary method</small></div><div><strong>${r.max}</strong><small>Max auto-charge</small></div><div><strong>${r.retry}</strong><small>${r.interval}</small></div><div><strong>${r.fallback}</strong><small>Fallback method</small></div><div><strong>${r.failure}</strong><small>Failure notification</small></div><div class="payment-row-actions"><button type="button" onclick="PaymentSettings.toggleAutoPayRule(${i})">${r.enabled === 'Enabled' ? 'Disable' : 'Enable'}</button><button type="button" onclick="PaymentSettings.testAutoPayRule(${i})">Test</button></div></div>`), 'payment-autopay-table')}${table(['Fee', 'Handling', 'Model', 'Value', 'Applies To', 'Status'], state.fees.map(f => `<div class="data-row payment-fee-row"><div><strong>${f.fee}</strong><small>${f.applies}</small></div><div><strong>${f.handling}</strong><small>Fee allocation</small></div><div><strong>${f.model}</strong><small>Calculation model</small></div><div><strong>${f.value}</strong><small>Fee value</small></div><div><strong>${f.applies}</strong><small>Scope</small></div><span class="badge ${tone(f.status)}">${f.status}</span></div>`), 'payment-fees-table')}</section>`;
      }
      function reconciliationExceptionQueue() {
        return table(['Exception', 'Source', 'Reference', 'Customer', 'Amount', 'Match Level', 'Issue', 'Actions'], state.reconciliationExceptions.map((x, i) => `<div class="data-row payment-recon-exception-row"><div><strong>${x.id}</strong><small>${x.action}</small></div><div><strong>${x.source}</strong><small>Imported source</small></div><div><strong>${x.reference}</strong><small>Payment reference</small></div><div><strong>${x.customer}</strong><small>Customer</small></div><div><strong>${x.amount}</strong><small>${x.currency}</small></div><span class="badge ${tone(x.match)}">${x.match}</span><div><strong>${x.issue}</strong><small>Exception reason</small></div><div class="payment-row-actions"><button type="button" onclick="PaymentSettings.matchException(${i})">Match</button><button type="button" onclick="PaymentSettings.ignoreException(${i})">Ignore</button></div></div>`), 'payment-recon-exception-table');
      }
      function reconciliation(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Reconciliation Settings</h2><p>Matching bank statements, payment gateways, ERP, accounting systems and marketplace settlement reports.</p></div><div class="payment-actions">${actionButton('Import Statement', 'PaymentSettings.importStatement()', 'primary-action')}${actionButton('Run Matching', 'PaymentSettings.runReconciliation()')}</div></div><div class="info-grid payment-info-grid"><div><span>Matching Rules</span><strong>Invoice · Customer · Ref · Amount · Currency</strong><small>Sender name and bank account included</small></div><div><span>Match Levels</span><strong>Exact · Partial · Probable · Unmatched</strong><small>Used for exception queues</small></div><div><span>Allocation Priority</span><strong>Fees → Penalties → Oldest invoices</strong><small>Then current invoices and deposit</small></div><div><span>Duplicate Detection</span><strong>Enabled</strong><small>Prevents double-posting</small></div></div>${table(['Source', 'Matches', 'Exact', 'Probable', 'Unmatched', 'Last Run', 'Status'], state.reconciliation.map(r => `<div class="data-row payment-recon-row"><div><strong>${r.source}</strong><small>Reconciliation source</small></div><div><strong>${r.matches}</strong><small>Total candidates</small></div><div><strong>${r.exact}</strong><small>Exact matches</small></div><div><strong>${r.probable}</strong><small>Probable</small></div><div><strong>${r.unmatched}</strong><small>Unmatched</small></div><div><strong>${r.lastRun}</strong><small>Last run</small></div><span class="badge ${tone(r.status)}">${r.status}</span></div>`), 'payment-recon-table')}<div class="payment-subsection"><h3>Reconciliation Exception Queue</h3><p class="muted">Manual review list for probable, partial and unmatched payments.</p>${reconciliationExceptionQueue()}</div></section>`;
      }
      function allocation(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Payment Allocation</h2><p>Controls how a confirmed payment is distributed across bank fees, penalties, overdue invoices, current invoices and deposit balance.</p></div><div class="payment-actions">${actionButton('Configure Priority', 'PaymentSettings.openAllocationModal()', 'primary-action')}${actionButton('Reallocate Payment', 'PaymentSettings.reallocatePayment()')}${actionButton('Run Allocation', 'PaymentSettings.runAllocation()')}</div></div><div class="commercial-governance-flow-v99 payment-flow payment-allocation-flow"><article><span>01</span><strong>Payment</strong><small>Confirmed incoming amount</small></article><article><span>02</span><strong>Bank Fees</strong><small>Processing and transfer fees</small></article><article><span>03</span><strong>Penalties</strong><small>Late payment fees</small></article><article><span>04</span><strong>Oldest Invoice</strong><small>Overdue receivables first</small></article><article><span>05</span><strong>Current / Deposit</strong><small>Current invoices then deposit</small></article></div>${table(['Priority', 'Bucket', 'Rule', 'Target', 'Status'], state.allocations.map(a => `<div class="data-row payment-allocation-row"><div><strong>${a.priority}</strong><small>Priority order</small></div><div><strong>${a.bucket}</strong><small>Allocation bucket</small></div><div><strong>${a.rule}</strong><small>Rule</small></div><div><strong>${a.target}</strong><small>Posting target</small></div><span class="badge ${tone(a.status)}">${a.status}</span></div>`), 'payment-allocation-table')}</section>`;
      }
      function notifications(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Payment Notifications</h2><p>Notification rules for invoice sent, payment received, payment failed, overdue invoice, refund completed, chargeback received and auto-payment failed.</p></div><div class="payment-actions">${actionButton('+ Add Notification Rule', 'PaymentSettings.openNotificationModal()', 'primary-action')}${actionButton('Test Notification', 'PaymentSettings.testNotification()')}</div></div>${table(['Event', 'Channels', 'Recipients', 'Template', 'Status', 'Actions'], state.notifications.map((n, i) => `<div class="data-row payment-notification-row"><div><strong>${n.event}</strong><small>Payment event</small></div><div><strong>${n.channels}</strong><small>Delivery channels</small></div><div><strong>${n.recipients}</strong><small>Recipients</small></div><div><strong>${n.template}</strong><small>Template code</small></div><span class="badge ${tone(n.status)}">${n.status}</span><div class="payment-row-actions"><button type="button" onclick="PaymentSettings.toggleNotification(${i})">${n.status === 'Active' ? 'Disable' : 'Activate'}</button><button type="button" onclick="PaymentSettings.testNotification(${i})">Test</button></div></div>`), 'payment-notification-table')}</section>`;
      }
      function refunds(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Refunds, Chargebacks & Disputes</h2><p>Refund approvals, partial refunds, refund reasons, chargeback evidence, response deadlines and dispute status.</p></div><div class="payment-actions">${actionButton('Request Refund', 'PaymentSettings.requestRefund()', 'primary-action')}${actionButton('Upload Evidence', 'PaymentSettings.uploadEvidence()')}${actionButton('Open Dispute Queue', 'PaymentSettings.openDisputeQueue()')}</div></div>${table(['ID', 'Customer', 'Payment', 'Amount', 'Reason', 'Approval', 'Destination', 'Status', 'Actions'], state.refunds.map((r, i) => `<div class="data-row payment-refund-row"><div><strong>${r.id}</strong><small>Refund / dispute</small></div><div><strong>${r.customer}</strong><small>Customer</small></div><div><strong>${r.payment}</strong><small>Payment ref</small></div><div><strong>${r.amount}</strong><small>Amount</small></div><div><strong>${r.reason}</strong><small>Reason</small></div><div><strong>${r.approval}</strong><small>Approval rule</small></div><div><strong>${r.destination}</strong><small>Destination</small></div><span class="badge ${tone(r.status)}">${r.status}</span><div class="payment-row-actions"><button type="button" onclick="PaymentSettings.approveRefund(${i})">Approve</button><button type="button" onclick="PaymentSettings.rejectRefund(${i})">Reject</button></div></div>`), 'payment-refund-table')}${table(['Dispute', 'Invoice', 'Customer', 'Amount', 'Reason', 'Deadline', 'Evidence', 'Status', 'Actions'], state.disputes.map((d, i) => `<div class="data-row payment-dispute-row"><div><strong>${d.id}</strong><small>Chargeback / dispute</small></div><div><strong>${d.invoice}</strong><small>Linked invoice</small></div><div><strong>${d.customer}</strong><small>Customer</small></div><div><strong>${d.amount}</strong><small>Disputed amount</small></div><div><strong>${d.reason}</strong><small>Reason</small></div><div><strong>${d.deadline}</strong><small>Response deadline</small></div><div><strong>${d.evidence}</strong><small>Evidence package</small></div><span class="badge ${tone(d.status)}">${d.status}</span><div class="payment-row-actions"><button type="button" onclick="PaymentSettings.reviewDispute(${i})">Review</button><button type="button" onclick="PaymentSettings.resolveDispute(${i})">Resolve</button></div></div>`), 'payment-dispute-table')}</section>`;
      }
      function payouts(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Payout Settings</h2><p>Marketplace and energy trading payout recipient, schedule, minimum amount, commission deduction, tax withholding and approval workflow.</p></div><div class="payment-actions">${actionButton('Run Payout Batch', 'PaymentSettings.runPayoutBatch()', 'primary-action')}</div></div>${table(['Recipient', 'Schedule', 'Minimum', 'Currency', 'Bank Account', 'Commission', 'Tax', 'Approval', 'Status'], state.payouts.map((p, i) => `<div class="data-row payment-payout-row"><div><strong>${p.recipient}</strong><small>Payout recipient</small></div><div><strong>${p.schedule}</strong><small>Schedule</small></div><div><strong>${p.minimum}</strong><small>Minimum amount</small></div><div><strong>${p.currency}</strong><small>Payout currency</small></div><div><strong>${p.bank}</strong><small>Payout bank account</small></div><div><strong>${p.commission}</strong><small>Deduction</small></div><div><strong>${p.withholding}</strong><small>Withholding</small></div><div><strong>${p.approval}</strong><small>Workflow</small></div><span class="badge ${tone(p.status)}">${p.status}</span></div>`), 'payment-payout-table')}</section>`;
      }
      function statusesSecurity(): string {
        const paymentStatuses = ['initiated', 'pending', 'processing', 'authorized', 'captured', 'partially_paid', 'paid', 'failed', 'cancelled', 'refunded', 'partially_refunded', 'chargeback', 'disputed', 'reversed'];
        const invoiceStatuses = ['draft', 'approved', 'sent', 'unpaid', 'partially_paid', 'paid', 'overdue', 'disputed', 'cancelled', 'written_off'];
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Status Dictionaries & Security</h2><p>Payment statuses, invoice payment statuses and mandatory security controls.</p></div><div class="payment-actions">${actionButton('Verify Security', 'PaymentSettings.verifySecurity()', 'primary-action')}</div></div><div class="payment-status-grid"><div><h3>Payment Statuses</h3><div class="payment-chip-list">${paymentStatuses.map(s => `<span class="badge ${tone(s)}">${s}</span>`).join('')}</div></div><div><h3>Invoice Payment Statuses</h3><div class="payment-chip-list">${invoiceStatuses.map(s => `<span class="badge ${tone(s)}">${s}</span>`).join('')}</div></div></div><div class="info-grid payment-info-grid"><div><span>PCI DSS</span><strong>Required for card payments</strong><small>Cards tokenized by provider</small></div><div><span>CVV Storage</span><strong>Forbidden</strong><small>Never stored in Zentrid</small></div><div><span>Secrets</span><strong>Encrypted</strong><small>API keys and secret keys encrypted</small></div><div><span>2FA</span><strong>Required</strong><small>For changing payment settings</small></div><div><span>Webhooks</span><strong>Signature verification</strong><small>IP whitelist supported</small></div><div><span>RBAC + Audit</span><strong>Enabled</strong><small>All sensitive actions logged</small></div></div></section>`;
      }
      function audit(): string {
        return `<section class="panel glass-card payment-panel"><div class="panel-head payment-head"><div><h2>Payment Audit Log</h2><p>Changes to bank details, gateway settings, payment terms, manual allocation, refunds, chargebacks, statuses and write-offs.</p></div><div class="payment-actions">${actionButton('Export Audit', 'PaymentSettings.exportAudit()', 'primary-action')}</div></div>${table(['Action', 'Entity', 'Old Value', 'New Value', 'Changed By', 'Changed At'], state.audit.map(a => `<div class="data-row payment-audit-row"><div><strong>${a.action}</strong><small>Audit action</small></div><div><strong>${a.entity}</strong><small>Entity</small></div><div><strong>${a.old}</strong><small>Before</small></div><div><strong>${a.next}</strong><small>After</small></div><div><strong>${a.by}</strong><small>User</small></div><div><strong>${a.at}</strong><small>Timestamp</small></div></div>`), 'payment-audit-table')}</section>`;
      }
      function content(tab: string = state.activeTab): string {
        const map: Record<string, () => string> = { overview, methods, gateways, banks, terms, profiles, autopayFxFees, allocation, reconciliation, refunds, notifications, payouts, statusesSecurity, audit };
        return (map[tab] || overview)();
      }
      function render(): void {
        FleetLayout.mount(`<section class="page-hero"><div><p class="eyebrow">Global Admin · Financial Operations</p><h1>Payment Settings</h1><p class="muted">Configure payment methods, payment gateways, bank accounts, payment terms, FX, fees, reconciliation, refunds, payouts, security and payment audit.</p></div><button class="secondary-action" onclick="location.href='billing-management.html'">Back to Billing Management</button></section><section class="plant-workspace-v17 payment-settings-workspace-v100 payment-v2"><aside class="glass-card plant-side-card-v17 payment-side"><h3>Payment Settings</h3>${[
          ['overview','Overview'], ['methods','Payment Methods'], ['gateways','Payment Gateways'], ['banks','Bank Accounts'], ['terms','Payment Terms'], ['profiles','Customer Profiles'], ['autopayFxFees','Auto-Pay · FX · Fees'], ['allocation','Payment Allocation'], ['reconciliation','Reconciliation'], ['refunds','Refunds & Disputes'], ['notifications','Notifications'], ['payouts','Payouts'], ['statusesSecurity','Statuses & Security'], ['audit','Audit Logs']
        ].map(([id, label]) => `<button class="${state.activeTab === id ? 'active' : ''}" data-payment-tab="${id}">${label}</button>`).join('')}</aside><section class="payment-main" id="paymentContent">${content()}</section></section>`);
      }
      function setTab(tab: string): void {
        state.activeTab = tab;
        document.querySelectorAll('[data-payment-tab]').forEach(b => b.classList.toggle('active', b.dataset.paymentTab === tab));
        const target = document.getElementById('paymentContent');
        if (target) target.innerHTML = content(tab);
      }
      function addAudit(action: string, entity: string, oldValue: string, newValue: string): void {
        state.audit.unshift({ action, entity, old: oldValue, next: newValue, by: 'Global Admin', at: new Date().toLocaleString('en-GB', { day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' }) });
      }
      function openMethodModal(index: number | null = null): void {
        const m = index !== null ? state.methods[index] : { code:'', name:'', type:'bank_transfer', currencies:'EUR', countries:'All', min:0, max:100000, fee:'0.00% + 0.00', settlement:'T+1', reconcile:'Yes', status:'Active' };
        if (!m) return;
        openModal(index === null ? 'Add Payment Method' : 'Edit Payment Method', `<div class="client-form-grid two-col">${input('Code','pmCode',m.code)}${input('Name','pmName',m.name)}${select('Type','pmType',['bank_transfer','card_gateway','direct_debit','swift','sepa','paypal','local_provider','internal_balance'],m.type)}${input('Currencies','pmCurrencies',m.currencies)}${input('Countries','pmCountries',m.countries)}${input('Min Amount','pmMin',m.min,'number')}${input('Max Amount','pmMax',m.max,'number')}${input('Processing Fee','pmFee',m.fee)}${input('Settlement Time','pmSettlement',m.settlement)}${select('Auto-Reconciliation','pmReconcile',['Yes','No','Auto'],m.reconcile)}${select('Status','pmStatus',['Active','Review','Disabled'],m.status)}</div>`, `<button class="secondary-action" type="button" onclick="PaymentSettings.closeModal()">Cancel</button><button class="primary-action" type="button" onclick="PaymentSettings.saveMethod(${index === null ? 'null' : index})">Save Method</button>`);
      }
      function saveMethod(index: number | null = null): void {
        const method = { code: val('pmCode'), name: val('pmName'), type: val('pmType'), currencies: val('pmCurrencies'), countries: val('pmCountries'), min: Number(val('pmMin') || 0), max: Number(val('pmMax') || 0), fee: val('pmFee'), settlement: val('pmSettlement'), reconcile: val('pmReconcile'), status: val('pmStatus') };
        if (!method.code || !method.name) return FleetLayout.toast('Code and name are required');
        if (index === null) state.methods.unshift(method); else state.methods[index] = method;
        addAudit(index === null ? 'Payment method created' : 'Payment method updated', method.code, '—', method.status);
        closeModal(); setTab('methods'); FleetLayout.toast('Payment method saved');
      }
      function toggleMethod(index: number): void {
        const m = state.methods[index];
        if (!m) return;
        const old = m.status;
        m.status = m.status === 'Active' ? 'Disabled' : 'Active';
        addAudit('Payment method status changed', m.code, old, m.status);
        setTab('methods');
      }
      function openGatewayModal(): void {
        openModal('Add Payment Gateway', `<div class="client-form-grid two-col">${input('Gateway Name','pgName')}${input('Provider Code','pgCode')}${select('Mode','pgMode',['Test','Production'])}${input('Merchant ID','pgMerchant')}${input('Webhook URL','pgWebhook','/payments/webhooks/provider')}${input('Callback URL','pgCallback','/payments/callback')}${input('Supported Currencies','pgCurrencies','EUR, USD')}${input('Supported Countries','pgCountries','Global')}${input('Transaction Fee','pgFee','2.90% + 0.30')}${select('Refund Support','pgRefund',['Yes','No','Manual'])}${select('Chargeback Support','pgChargeback',['Yes','No'])}${input('Payout Schedule','pgPayout','Daily')}${select('Webhook Signature','pgSignature',['Enabled','Review','Disabled'])}${select('IP Whitelist','pgIpWhitelist',['Enabled','Review','Disabled'])}</div>`, `<button class="secondary-action" type="button" onclick="PaymentSettings.closeModal()">Cancel</button><button class="primary-action" type="button" onclick="PaymentSettings.saveGateway()">Save Gateway</button>`);
      }
      function saveGateway(): void {
        const gateway = { provider: val('pgName'), code: val('pgCode'), mode: val('pgMode'), merchant: val('pgMerchant'), currencies: val('pgCurrencies'), countries: val('pgCountries'), fee: val('pgFee'), refund: val('pgRefund'), chargeback: val('pgChargeback'), payout: val('pgPayout'), status: 'Review', webhookSignature: val('pgSignature'), keysEncrypted: 'Yes', ipWhitelist: val('pgIpWhitelist'), apiKey: 'Encrypted', secretKey: 'Encrypted' };
        if (!gateway.provider || !gateway.code) return FleetLayout.toast('Gateway name and provider code are required');
        state.gateways.unshift(gateway); addAudit('Payment gateway created', gateway.provider, '—', gateway.mode); closeModal(); setTab('gateways'); FleetLayout.toast('Gateway saved as review');
      }
      function openBankModal(): void {
        openModal('Add Platform Bank Account', `<div class="client-form-grid two-col">${input('Legal Entity','baEntity','Zentrid Global Ltd')}${input('Bank Name','baBank')}${input('Account Number / IBAN','baAccount')}${input('SWIFT / BIC','baSwift')}${select('Currency','baCurrency',['EUR','USD','AMD','GBP'])}${input('Country','baCountry','Armenia')}${input('Beneficiary Name','baBeneficiary','Zentrid Global Ltd')}${input('Correspondent Bank','baCorrespondent','—')}${input('Payment Purpose Template','baPurpose','Invoice {{invoice_no}}')}</div>`, `<button class="secondary-action" type="button" onclick="PaymentSettings.closeModal()">Cancel</button><button class="primary-action" type="button" onclick="PaymentSettings.saveBank()">Save Bank Account</button>`);
      }
      function saveBank(): void {
        const bank = { entity: val('baEntity'), bank: val('baBank'), account: val('baAccount'), swift: val('baSwift'), currency: val('baCurrency'), country: val('baCountry'), beneficiary: val('baBeneficiary'), correspondent: val('baCorrespondent'), purpose: val('baPurpose'), status: 'Draft' };
        state.banks.unshift(bank); addAudit('Bank account created', bank.bank, '—', bank.currency); closeModal(); setTab('banks'); FleetLayout.toast('Bank account saved as draft');
      }
      function openTermModal(): void {
        openModal('Add Payment Term', `<div class="client-form-grid two-col">${input('Payment Term Code','ptCode')}${input('Payment Term Name','ptName')}${input('Due Days','ptDue',15,'number')}${input('Grace Period','ptGrace',5,'number')}${input('Late Payment Fee','ptPenalty','0.05% / day')}${select('Penalty Frequency','ptFrequency',['Daily','Weekly','Monthly','None'])}${select('Auto-Reminder','ptReminder',['Enabled','Disabled'])}${input('Service Suspension Rule','ptSuspension','Day 45')}</div>`, `<button class="secondary-action" type="button" onclick="PaymentSettings.closeModal()">Cancel</button><button class="primary-action" type="button" onclick="PaymentSettings.saveTerm()">Save Term</button>`);
      }
      function saveTerm(): void {
        const term = { code: val('ptCode'), name: val('ptName'), due: Number(val('ptDue')||0), grace: Number(val('ptGrace')||0), penalty: val('ptPenalty'), frequency: val('ptFrequency'), reminders: val('ptReminder'), suspension: val('ptSuspension') };
        if (!term.code || !term.name) return FleetLayout.toast('Term code and name are required');
        state.terms.unshift(term); addAudit('Payment term created', term.code, '—', term.name); closeModal(); setTab('terms'); FleetLayout.toast('Payment term saved');
      }
      function approveRefund(index: number): void { const r = state.refunds[index]; if (!r) return; const old = r.status; r.status = 'Approved'; addAudit('Refund approved', r.id, old, r.status); setTab('refunds'); FleetLayout.toast(`${r.id} approved`); }
      function rejectRefund(index: number): void { const r = state.refunds[index]; if (!r) return; const old = r.status; r.status = 'Rejected'; addAudit('Refund rejected', r.id, old, r.status); setTab('refunds'); FleetLayout.toast(`${r.id} rejected`); }
      function runReconciliation(): void { state.reconciliation.forEach(r => { r.exact += r.probable; r.probable = 0; r.unmatched = Math.max(0, r.unmatched - 1); r.status = r.unmatched ? 'Review' : 'Matched'; r.lastRun = new Date().toLocaleString('en-GB', { day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' }); }); state.reconciliationExceptions.forEach(x => { if (x.match === 'Probable') { x.match = 'Exact'; x.action = 'Ready to Allocate'; } }); addAudit('Reconciliation run', 'All payment sources', 'pending', 'completed'); setTab('reconciliation'); FleetLayout.toast('Reconciliation completed'); }
      function advancePaymentFlow(): void { const next = state.invoiceFlow.find(f => f.status !== 'Done'); if (next) { const old = next.status; next.status = 'Done'; addAudit('Payment flow advanced', next.label, old, 'Done'); } else { state.invoiceFlow.forEach((f, i) => f.status = i < 2 ? 'Done' : 'Pending'); addAudit('Payment flow reset', 'Invoice payment flow', 'completed', 'new cycle'); } setTab('overview'); FleetLayout.toast('Invoice payment flow updated'); }
      function toggleGatewayMode(index: number): void { const g = state.gateways[index]; if (!g) return; const old = g.mode; g.mode = g.mode === 'Production' ? 'Test' : 'Production'; addAudit('Gateway mode changed', g.provider, old, g.mode); setTab('gateways'); FleetLayout.toast(`${g.provider} mode changed to ${g.mode}`); }
      function rotateGatewayKeys(index: number): void { const g = state.gateways[index]; if (!g) return; g.apiKey = 'Rotated'; g.secretKey = 'Rotated'; g.keysEncrypted = 'Yes'; addAudit('Gateway keys rotated', g.provider, 'previous encrypted keys', 'rotated encrypted keys'); setTab('gateways'); FleetLayout.toast(`${g.provider} keys rotated`); }
      function matchException(index: number): void { const x = state.reconciliationExceptions[index]; if (!x) return; addAudit('Reconciliation exception matched', x.id, x.match, 'Exact'); state.reconciliationExceptions.splice(index, 1); state.reconciliation.forEach(r => { if (r.unmatched > 0) r.unmatched -= 1; }); setTab('reconciliation'); FleetLayout.toast('Exception matched and removed from queue'); }
      function ignoreException(index: number): void { const x = state.reconciliationExceptions[index]; if (!x) return; addAudit('Reconciliation exception ignored', x.id, x.match, 'ignored'); state.reconciliationExceptions.splice(index, 1); setTab('reconciliation'); FleetLayout.toast('Exception ignored'); }
      function runPayoutBatch(): void { state.payouts.forEach(p => { if (p.status === 'Ready') p.status = 'Processed'; }); addAudit('Payout batch processed', 'Marketplace / Trading payouts', 'ready', 'processed'); setTab('payouts'); FleetLayout.toast('Payout batch processed'); }
      function testWebhooks(): void { addAudit('Webhook test executed', 'Payment gateways', 'not tested', 'success'); FleetLayout.toast('Webhook test successful'); }
      function verifySecurity(): void { addAudit('Payment security verified', 'Security settings', 'pending', 'verified'); FleetLayout.toast('Security checklist passed'); }
      function exportSettings(): void { FleetLayout.toast('Payment settings export prepared'); }
      function importStatement(): void { addAudit('Bank statement imported', 'Reconciliation', '—', 'statement uploaded'); FleetLayout.toast('Statement imported'); }
      function requestRefund(): void { const id = `RF-${Math.floor(1050 + Math.random()*100)}`; state.refunds.unshift({ id, customer:'Manual Request', payment:'PAY-MANUAL', amount:'€0.00', reason:'Manual refund', approval:'Finance Manager', destination:'Original method', status:'Requested' }); addAudit('Refund requested', id, '—', 'requested'); setTab('refunds'); }
      function openDisputeQueue(): void { setTab('refunds'); FleetLayout.toast('Dispute queue opened'); }
      function openProfileModal(index: number | null = null): void {
        const p = index !== null ? state.profiles[index] : { customer:'', method:'Bank Transfer', currency:'EUR', email:'', tax:'', term:'Net 15', credit:'€0', deposit:'€0', auto:'No', format:'PDF', contact:'' };
        if (!p) return;
        openModal(index === null ? 'Add Customer Payment Profile' : 'Edit Customer Payment Profile', `<div class="client-form-grid two-col">${input('Customer','cpCustomer',p.customer)}${input('Payment Contact Person','cpContact',p.contact)}${select('Default Payment Method','cpMethod',state.methods.map(m => m.name),p.method)}${select('Default Currency','cpCurrency',['EUR','USD','AMD','GBP'],p.currency)}${input('Billing Email','cpEmail',p.email)}${input('Tax Number','cpTax',p.tax)}${select('Payment Term','cpTerm',state.terms.map(t => t.name),p.term)}${input('Credit Limit','cpCredit',p.credit)}${input('Deposit Balance','cpDeposit',p.deposit)}${select('Auto Payment Enabled','cpAuto',['Yes','No'],p.auto)}${select('Preferred Invoice Format','cpFormat',['PDF','PDF + XLSX','XML','EDI'],p.format)}</div>`, `<button class="secondary-action" type="button" onclick="PaymentSettings.closeModal()">Cancel</button><button class="primary-action" type="button" onclick="PaymentSettings.saveProfile(${index === null ? 'null' : index})">Save Profile</button>`);
      }
      function saveProfile(index: number | null = null): void {
        const profile = { customer: val('cpCustomer'), method: val('cpMethod'), currency: val('cpCurrency'), email: val('cpEmail'), tax: val('cpTax'), term: val('cpTerm'), credit: val('cpCredit'), deposit: val('cpDeposit'), auto: val('cpAuto'), format: val('cpFormat'), contact: val('cpContact') };
        if (!profile.customer || !profile.email) return FleetLayout.toast('Customer and billing email are required');
        if (index === null) state.profiles.unshift(profile); else state.profiles[index] = profile;
        addAudit(index === null ? 'Customer payment profile created' : 'Customer payment profile updated', profile.customer, '—', profile.method); closeModal(); setTab('profiles'); FleetLayout.toast('Customer payment profile saved');
      }
      function resetProfile(index: number): void { const p = state.profiles[index]; if (!p) return; const old = `${p.method} / ${p.term}`; p.method = 'Bank Transfer'; p.auto = 'No'; p.format = 'PDF'; addAudit('Customer payment profile reset', p.customer, old, 'default profile'); setTab('profiles'); FleetLayout.toast(`${p.customer} payment profile reset`); }
      function testPaymentRoute(): void { addAudit('Payment route tested', 'Customer Payment Profile', 'not tested', 'success'); FleetLayout.toast('Payment route test successful'); }
      function openAutoPayRuleModal(): void { openModal('Create Auto-Payment Rule', `<div class="client-form-grid two-col">${input('Rule Name','apName')}${input('Scope','apScope','Monthly subscription')}${select('Enabled','apEnabled',['Enabled','Review','Disabled'])}${select('Payment Method','apMethod',state.methods.map(m => m.name))}${input('Maximum Auto-Charge Amount','apMax','€1,000')}${input('Retry Attempts','apRetry','3 attempts')}${input('Retry Interval','apInterval','24h')}${select('Fallback Method','apFallback',['Bank Transfer','Card Payment · Stripe','Manual approval','Client Deposit Balance'])}${select('Failure Notification','apFailure',['Email + In-App','Webhook + Email','Finance escalation'])}</div>`, `<button class="secondary-action" type="button" onclick="PaymentSettings.closeModal()">Cancel</button><button class="primary-action" type="button" onclick="PaymentSettings.saveAutoPayRule()">Save Rule</button>`); }
      function saveAutoPayRule(): void { const rule = { name: val('apName'), scope: val('apScope'), enabled: val('apEnabled'), method: val('apMethod'), max: val('apMax'), retry: val('apRetry'), interval: val('apInterval'), fallback: val('apFallback'), failure: val('apFailure') }; if (!rule.name) return FleetLayout.toast('Rule name is required'); state.autoPayRules.unshift(rule); addAudit('Auto-payment rule created', rule.name, '—', rule.enabled); closeModal(); setTab('autopayFxFees'); FleetLayout.toast('Auto-payment rule saved'); }
      function toggleAutoPayRule(index: number): void { const r = state.autoPayRules[index]; if (!r) return; const old = r.enabled; r.enabled = r.enabled === 'Enabled' ? 'Disabled' : 'Enabled'; addAudit('Auto-payment rule status changed', r.name, old, r.enabled); setTab('autopayFxFees'); }
      function testAutoPayRule(index: number | null = null): void { const name = index === null ? 'Selected rule' : state.autoPayRules[index]?.name || 'Selected rule'; addAudit('Auto-payment rule tested', name, 'not tested', 'success'); FleetLayout.toast(`${name} test successful`); }
      function refreshFx(): void { FleetLayout.toast('FX rates refreshed'); addAudit('FX rates refreshed', 'Currency settings', 'old rates', 'latest rates'); }
      function openAllocationModal(): void { openModal('Configure Allocation Priority', `<div class="client-form-grid two-col">${select('Priority 1','al1',['Bank Fees','Penalties','Oldest Overdue Invoices'])}${select('Priority 2','al2',['Penalties','Bank Fees','Oldest Overdue Invoices'])}${select('Priority 3','al3',['Oldest Overdue Invoices','Current Invoices','Deposit Balance'])}${select('Priority 4','al4',['Current Invoices','Deposit Balance'])}${select('Priority 5','al5',['Deposit Balance','Current Invoices'])}</div>`, `<button class="secondary-action" type="button" onclick="PaymentSettings.closeModal()">Cancel</button><button class="primary-action" type="button" onclick="PaymentSettings.saveAllocationPriority()">Save Priority</button>`); }
      function saveAllocationPriority(): void { addAudit('Payment allocation priority changed', 'Allocation Rules', 'previous priority', 'updated priority'); closeModal(); setTab('allocation'); FleetLayout.toast('Allocation priority saved'); }
      function reallocatePayment(): void { addAudit('Payment manually reallocated', 'PAY-9921', 'old allocation', 'new allocation'); FleetLayout.toast('Payment reallocated'); }
      function runAllocation(): void { addAudit('Payment allocation run', 'Open payments', 'pending allocation', 'allocated'); FleetLayout.toast('Allocation run completed'); }
      function uploadEvidence(): void { state.disputes.forEach(d => { if (d.status === 'Evidence Required') { d.evidence = 'Uploaded'; d.status = 'Under Review'; } }); addAudit('Dispute evidence uploaded', 'Chargeback queue', 'required', 'uploaded'); setTab('refunds'); FleetLayout.toast('Evidence uploaded'); }
      function reviewDispute(index: number): void { const d = state.disputes[index]; if (!d) return; d.status = 'Under Review'; addAudit('Dispute reviewed', d.id, 'open', 'under review'); setTab('refunds'); FleetLayout.toast(`${d.id} opened for review`); }
      function resolveDispute(index: number): void { const d = state.disputes[index]; if (!d) return; const old = d.status; d.status = 'Resolved'; d.evidence = 'Complete'; addAudit('Dispute resolved', d.id, old, 'resolved'); setTab('refunds'); FleetLayout.toast(`${d.id} resolved`); }
      function openNotificationModal(): void { openModal('Add Payment Notification Rule', `<div class="client-form-grid two-col">${input('Event','ntEvent','Payment Failed')}${input('Channels','ntChannels','Email · In-App')}${input('Recipients','ntRecipients','Billing contact + finance')}${input('Template Code','ntTemplate','payment_event_v1')}${select('Status','ntStatus',['Active','Review','Disabled'])}</div>`, `<button class="secondary-action" type="button" onclick="PaymentSettings.closeModal()">Cancel</button><button class="primary-action" type="button" onclick="PaymentSettings.saveNotification()">Save Rule</button>`); }
      function saveNotification(): void { const item = { event: val('ntEvent'), channels: val('ntChannels'), recipients: val('ntRecipients'), template: val('ntTemplate'), status: val('ntStatus') }; if (!item.event) return FleetLayout.toast('Event is required'); state.notifications.unshift(item); addAudit('Payment notification rule created', item.event, '—', item.status); closeModal(); setTab('notifications'); FleetLayout.toast('Notification rule saved'); }
      function toggleNotification(index: number): void { const n = state.notifications[index]; if (!n) return; const old = n.status; n.status = n.status === 'Active' ? 'Disabled' : 'Active'; addAudit('Payment notification rule changed', n.event, old, n.status); setTab('notifications'); }
      function testNotification(index: number | null = null): void { const event = index === null ? 'Selected notification' : state.notifications[index]?.event || 'Selected notification'; addAudit('Payment notification tested', event, 'not sent', 'sent'); FleetLayout.toast(`${event} test sent`); }
      function updateProfile(): void { openProfileModal(); }
      function exportAudit(): void { FleetLayout.toast('Payment audit export prepared'); }
      function val(id: string): string { return (document.getElementById(id) as HTMLInputElement | HTMLSelectElement | null)?.value?.trim() || ''; }
      function init(): void { render(); document.addEventListener('click', (e: Event) => { const b = (e.target as HTMLElement | null)?.closest('[data-payment-tab]') as HTMLElement | null; if (b?.dataset.paymentTab) setTab(b.dataset.paymentTab); }); }
      return { init, setTab, closeModal, openMethodModal, saveMethod, toggleMethod, openGatewayModal, saveGateway, toggleGatewayMode, rotateGatewayKeys, openBankModal, saveBank, openTermModal, saveTerm, approveRefund, rejectRefund, runReconciliation, advancePaymentFlow, matchException, ignoreException, runPayoutBatch, testWebhooks, verifySecurity, exportSettings, importStatement, requestRefund, openDisputeQueue, refreshFx, updateProfile, exportAudit, openProfileModal, saveProfile, resetProfile, testPaymentRoute, openAutoPayRuleModal, saveAutoPayRule, toggleAutoPayRule, testAutoPayRule, openAllocationModal, saveAllocationPriority, reallocatePayment, runAllocation, uploadEvidence, reviewDispute, resolveDispute, openNotificationModal, saveNotification, toggleNotification, testNotification };
    })();
    PaymentSettings.init();
