(() => {
interface ProductionNormalizationField { field_key?: string; ui_label?: string; domain?: string; category?: string; description?: string; normalization_rule?: string; used_in?: string[]; unit?: string; entity?: string; data_type?: string; required_level?: string; time_scope?: string; }
interface ProductionNormalizationScreenSection { fields?: string[]; }
interface ProductionNormalizationScreen { screen_id?: string; screen_name?: string; primary_entities?: string[]; sections?: ProductionNormalizationScreenSection[]; }
interface ProductionNormalizationState { tab: string; fields: ProductionNormalizationField[]; screens: ProductionNormalizationScreen[]; }
const PATH_FIELDS = '../assets/data/Zentrid_UI_Field_Dictionary_v1.json';
    const PATH_SCREENS = '../assets/data/Zentrid_UI_Screens_v1.json';
    const state: ProductionNormalizationState = { tab:'overview', fields:[], screens:[] };
    function esc(v: unknown): string{const entities: Record<string,string>={'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'};return String(v??'').replace(/[&<>'"]/g,c=>entities[c]??c);}
    function badge(v: unknown): string{const s=String(v||'').toLowerCase();return `<span class="badge ${s.includes('required')||s.includes('active')?'success':s.includes('optional')?'neutral':'warning'}">${esc(v)}</span>`;}
    async function init(): Promise<void>{
      const [fd, sc] = await Promise.all([fetch(PATH_FIELDS,{cache:'no-store'}).then(r=>r.json()), fetch(PATH_SCREENS,{cache:'no-store'}).then(r=>r.json())]);
      state.fields = fd.fields || [];
      state.screens = sc.screens || [];
      render();
    }
    function productionFields(): ProductionNormalizationField[]{
      const terms=['power','energy','yield','generation','production','export','import','load','irradiance','consumption','specific_yield','performance'];
      return state.fields.filter(f=>{
        const hay=[f.field_key,f.ui_label,f.domain,f.category,f.description,f.normalization_rule,(f.used_in||[]).join(' ')].join(' ').toLowerCase();
        return terms.some(t=>hay.includes(t)) && !hay.includes('battery detail') && !hay.includes('storage');
      });
    }
    function unitRows(): ProductionNormalizationField[]{
      return productionFields().filter(f=>['kW','kWh','MWh','W/m2','%','Hz','V','A','kVA','kVAr'].includes(f.unit || '')).slice(0,60);
    }
    function screenUsage(): ProductionNormalizationScreen[]{
      const ids=['plant_list','plant_detail','telemetry','historical_data','energy_flow','weather_station','meter_epm'];
      return state.screens.filter(s=>ids.includes(s.screen_id || ''));
    }
    function mappingRows(): string{
      return unitRows().map((f,i)=>`<div class="data-row production-mapping-row-v93"><div><strong>${esc(f.ui_label)}</strong><small>${esc(f.field_key)}</small></div><div><strong>${esc((f.used_in||[]).join(' · ')||f.category)}</strong><small>${esc(f.entity||'Zentrid field')}</small></div><div><strong>${esc(f.unit||'—')}</strong><small>Canonical unit</small></div><div><strong>${esc(f.normalization_rule||'Use normalized Zentrid value')}</strong><small>${esc(f.data_type||'value')}</small></div>${badge(f.required_level||'Optional')}<div class="row-actions"><button class="small-btn" onclick="ZentridLayout.toast('Field dictionary record: ${esc(f.field_key)}')">Open</button></div></div>`).join('');
    }
    function tabs(): string{return `<aside class="glass-card production-side-card-v92"><h3>Production Workspace</h3>${[['overview','Overview'],['fields','Canonical Fields'],['screens','Screen Usage'],['units','Units & Rules'],['quality','Validation Rules']].map(([id,label])=>`<button class="${state.tab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}</aside>`;}
    function overview(): string{const pf=productionFields();const used=[...new Set(pf.flatMap(f=>f.used_in||[]))];const units=[...new Set(pf.map(f=>f.unit).filter(Boolean))];return `<div class="section-title-v17"><div><h2>Production Normalization Overview</h2><p class="muted">This page is now driven by the UI Dictionary and Screen Contract. It no longer uses random vendor mock metrics.</p></div></div><section class="kpi-grid compact-kpis"><article class="kpi-card cyan"><span>Production Fields</span><strong>${pf.length}</strong><small>deduplicated Zentrid UI fields</small></article><article class="kpi-card green"><span>Screen Coverage</span><strong>${used.length}</strong><small>${esc(used.slice(0,4).join(' · '))}</small></article><article class="kpi-card blue"><span>Canonical Units</span><strong>${units.length}</strong><small>${esc(units.slice(0,7).join(' · '))}</small></article><article class="kpi-card yellow"><span>Rule Source</span><strong>Dictionary</strong><small>single UI dictionary</small></article></section><div class="normalization-empty-grid"><article><strong>Plant</strong><small>Use Plant everywhere. Do not use Site or Station as product labels.</small></article><article><strong>Device</strong><small>Use Device everywhere. Do not use Asset or Equipment as UI labels.</small></article><article><strong>Power</strong><small>Normalize power to kW and energy to kWh according to field dictionary units.</small></article><article><strong>Temperature</strong><small>Use °C only. Non-canonical temperature examples were removed.</small></article></div>`;}
    function fields(): string{return `<div class="section-title-v17"><div><h2>Canonical Production Fields</h2><p class="muted">Field names, labels, units and normalization rules from the shared UI Dictionary.</p></div></div><div class="data-table"><div class="data-head production-mapping-row-v93"><span>UI Label</span><span>Used In</span><span>Unit</span><span>Normalization Rule</span><span>Level</span><span>Actions</span></div><div class="production-mapping-rows-v93">${mappingRows()}</div></div>`;}
    function screens(): string{return `<div class="section-title-v17"><div><h2>Production Screen Usage</h2><p class="muted">Same field key can be reused across Plant, Telemetry, Historical and Energy Flow screens with the same label.</p></div></div><div class="data-table normalized-screen-table-v4"><div class="data-head"><span>Screen</span><span>Primary Entities</span><span>Field References</span><span>Governance Rule</span></div>${screenUsage().map(s=>{const count=(s.sections||[]).reduce((a,sec)=>a+(sec.fields||[]).length,0);return `<div class="data-row"><div><strong>${esc(s.screen_name)}</strong><small>${esc(s.screen_id)}</small></div><div><strong>${esc((s.primary_entities||[]).join(' · ')||'Plant · Device')}</strong><small>normalized entities</small></div><div><strong>${count}</strong><small>shared field keys</small></div><div><strong>Use shared labels</strong><small>No local synonyms</small></div></div>`}).join('')}</div>`;}
    function units(): string{const rows=unitRows();return `<div class="section-title-v17"><div><h2>Units & Normalization Rules</h2><p class="muted">These units are the only display targets for production and energy fields.</p></div></div><div class="data-table production-unit-table-v5"><div class="data-head production-unit-row-v5"><span>Field Key</span><span>Label</span><span>Canonical Unit</span><span>Rule</span></div>${rows.map(f=>`<div class="data-row production-unit-row-v5"><div><strong>${esc(f.field_key)}</strong><small>${esc(f.category)}</small></div><div><strong>${esc(f.ui_label)}</strong><small>${esc(f.entity)}</small></div><div><strong>${esc(f.unit||'—')}</strong><small>display unit</small></div><div><strong>${esc(f.normalization_rule||'Use normalized value')}</strong><small>${esc(f.time_scope||'')}</small></div></div>`).join('')}</div>`;}
    function quality(): string{return `<div class="section-title-v17"><div><h2>Validation Rules</h2><p class="muted">Production records must pass these checks before UI, reports or analytics use them.</p></div></div><div class="check-list unified-check-list"><label class="check-row done"><input type="checkbox" checked><span><b>Use canonical field key only</b><small>No screen-specific aliases for the same value.</small></span></label><label class="check-row done"><input type="checkbox" checked><span><b>Power uses kW</b><small>W/MW source values must be converted before display.</small></span></label><label class="check-row done"><input type="checkbox" checked><span><b>Energy uses kWh</b><small>MWh source values must be converted to kWh when target unit requires it.</small></span></label><label class="check-row done"><input type="checkbox" checked><span><b>Temperature uses °C</b><small>No non-canonical temperature labels in normalized UI.</small></span></label></div>`;}
    function active(): string{return state.tab==='fields'?fields():state.tab==='screens'?screens():state.tab==='units'?units():state.tab==='quality'?quality():overview();}
    function render(): void{ZentridLayout.mount(`<section class="page-hero production-hero"><div><p class="eyebrow">Global Admin · Data Governance</p><h1>Production Normalization</h1><p class="muted">Canonical production, energy and telemetry UI fields from Zentrid normalization layer.</p></div><button class="freshness-card" onclick="ZentridLayout.toast('Production normalization loaded')"><span class="pulse"></span><div><strong>Dictionary driven</strong><small>UI Dictionary</small></div></button></section><section class="production-workspace-v92">${tabs()}<section class="glass-card production-main-card-v92">${active()}</section></section>`);document.querySelectorAll<HTMLElement>('[data-tab]').forEach((b: HTMLElement)=>{b.onclick=()=>{state.tab=b.dataset.tab || 'overview';render();};});}
    init();
})();
