(() => {
interface SettlementCenterRun { id: string; seller: string; buyer: string; channel: string; period: string; energy: string; price: string; gross: number; fees: number; net: number; split: string; status: string; }
interface SettlementCenterAgreement { id: string; seller: string; buyer: string; channel: string; price: string; period: string; destination: string; status: string; }
const settlements: SettlementCenterRun[] = [
      { id:'SET-2026-06-001', seller:'Arpi Solar Group', buyer:'Green Market Trader LLC', channel:'Aggregator Contract', period:'June 2026', energy:'84,800 kWh', price:'€0.092 / kWh', gross:7801.60, fees:390.08, net:7411.52, split:'Owner 90% · Operator 7% · Platform 3%', status:'Ready for invoice' },
      { id:'SET-2026-06-002', seller:'Green Valley Estate', buyer:'Green Valley Mall', channel:'Direct PPA', period:'June 2026', energy:'545,500 kWh', price:'$0.118 / kWh', gross:64369.00, fees:1287.38, net:63081.62, split:'Owner 94% · Platform 2% · Service 4%', status:'Settled' },
      { id:'SET-2026-06-003', seller:'Ivan Petrov', buyer:'Local Distribution Grid', channel:'Grid Feed-in', period:'June 2026', energy:'610 kWh', price:'€0.065 / kWh', gross:39.65, fees:0, net:39.65, split:'Owner 100%', status:'Blocked by accounting' },
      { id:'SET-2026-06-004', seller:'Arpi Solar Group', buyer:'Aggregator Pool', channel:'BESS Dispatch', period:'June 2026', energy:'17,100 kWh', price:'€0.105 / kWh', gross:1795.50, fees:125.69, net:1669.81, split:'Owner 88% · Aggregator 9% · Platform 3%', status:'Ready for payout' }
    ];
    const agreements: SettlementCenterAgreement[] = [
      { id:'ESA-001', seller:'Arpi Solar Group', buyer:'Green Market Trader LLC', channel:'Aggregator Contract', price:'€0.092 / kWh', period:'Monthly', destination:'ACBA Bank · EUR', status:'Active' },
      { id:'ESA-002', seller:'Green Valley Estate', buyer:'Green Valley Mall', channel:'Direct PPA', price:'$0.118 / kWh', period:'Custom PPA schedule', destination:'HSBC · USD', status:'Active' },
      { id:'ESA-003', seller:'Ivan Petrov', buyer:'Local Distribution Grid', channel:'Feed-in agreement', price:'€0.065 / kWh', period:'Monthly', destination:'Ameriabank · EUR', status:'Review' }
    ];
    function tone(value: unknown): string{ const v=String(value||'').toLowerCase(); if(v.includes('active')||v.includes('settled')||v.includes('ready')) return 'success'; if(v.includes('review')||v.includes('payout')) return 'warning'; if(v.includes('blocked')) return 'danger'; return 'info'; }
    function money(value: unknown, currency = 'EUR'): string{ const symbol=currency==='USD'?'$':'€'; return symbol + Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}); }
    const totalGross = settlements.reduce((s: number, r: SettlementCenterRun): number=>s+Number(r.gross||0),0);
    const totalNet = settlements.reduce((s: number, r: SettlementCenterRun): number=>s+Number(r.net||0),0);
    function settlementRow(r: SettlementCenterRun): string{ return `<div class="data-row settlement-row-v160"><div><strong>${r.id}</strong><small>${r.period}</small></div><div><strong>${r.seller}</strong><small>Buyer: ${r.buyer}</small></div><div><strong>${r.channel}</strong><small>${r.energy} · ${r.price}</small></div><div><strong>${money(r.gross, r.price.includes('$')?'USD':'EUR')}</strong><small>Fees ${money(r.fees, r.price.includes('$')?'USD':'EUR')}</small></div><div><strong>${money(r.net, r.price.includes('$')?'USD':'EUR')}</strong><small>${r.split}</small></div><div><span class="badge ${tone(r.status)}">${r.status}</span></div></div>`; }
    function agreementRow(a: SettlementCenterAgreement): string{ return `<div class="data-row settlement-agreement-row-v160"><div><strong>${a.id}</strong><small>${a.seller}</small></div><div><strong>${a.buyer}</strong><small>${a.channel}</small></div><div><strong>${a.price}</strong><small>${a.period}</small></div><div><strong>${a.destination}</strong></div><div><span class="badge ${tone(a.status)}">${a.status}</span></div></div>`; }
    const rows = settlements.map(settlementRow).join('');
    const agreementRows = agreements.map(agreementRow).join('');

    function ensurePanel(id: string, className = 'modal'): HTMLElement{
      let el = document.getElementById(id);
      if(!el){ el = document.createElement('div'); el.id = id; el.className = className; document.body.appendChild(el); }
      return el;
    }
    function closePanel(id: string): void{ const el = document.getElementById(id); if(el) el.classList.remove('open'); }
    function fieldValue(id: string): string{ return ((document.getElementById(id) as HTMLInputElement | HTMLSelectElement | null)?.value || '').trim(); }

    window.SettlementCenter = {
      createRun(): void{
        const modal = ensurePanel('settlementModal');
        modal.innerHTML = `<div class="modal-card"><button class="modal-close" type="button" onclick="SettlementCenter.closeModal()">×</button><div class="panel-head"><div><h2>Create Settlement Run</h2><p>Convert approved Energy Ledger entries into invoiceable or payout-ready commercial settlement.</p></div><span class="badge success">Settlement Wizard</span></div><div class="client-form-grid two-col"><label>Settlement Period<select id="setPeriod"><option>June 2026</option><option>May 2026</option><option>Custom Period</option></select></label><label>Seller<select id="setSeller"><option>Arpi Solar Group</option><option>Green Valley Estate</option><option>Ivan Petrov</option></select></label><label>Buyer<select id="setBuyer"><option>Green Market Trader LLC</option><option>Local Distribution Grid</option><option>Aggregator Pool</option><option>Direct PPA Buyer</option></select></label><label>Sales Channel<select id="setChannel"><option>Aggregator Contract</option><option>Grid Feed-in</option><option>Direct PPA</option><option>BESS Dispatch</option><option>Marketplace</option></select></label><label>Exported Energy, kWh<input id="setEnergy" type="number" value="84800" /></label><label>Price per kWh<input id="setPrice" type="number" step="0.001" value="0.092" /></label><label>Currency<select id="setCurrency"><option>EUR</option><option>USD</option><option>AMD</option></select></label><label>Platform Fee, %<input id="setFee" type="number" value="5" /></label><label class="wide-field">Revenue Split<input id="setSplit" value="Owner 90% · Operator 7% · Platform 3%" /></label></div><div class="modal-actions"><button class="secondary-action" type="button" onclick="SettlementCenter.closeModal()">Cancel</button><button class="primary-action" type="button" onclick="SettlementCenter.saveRun()">Create Settlement Run</button></div></div>`;
        modal.classList.add('open');
      },
      saveRun(): void{
        const energy = Number(fieldValue('setEnergy') || 0);
        const price = Number(fieldValue('setPrice') || 0);
        const feePct = Number(fieldValue('setFee') || 0);
        const gross = energy * price;
        const fees = gross * feePct / 100;
        const rec = { id:`SET-2026-06-${String(settlements.length+1).padStart(3,'0')}`, seller:fieldValue('setSeller') || 'Arpi Solar Group', buyer:fieldValue('setBuyer') || 'Green Market Trader LLC', channel:fieldValue('setChannel') || 'Aggregator Contract', period:fieldValue('setPeriod') || 'June 2026', energy:`${energy.toLocaleString()} kWh`, price:`${fieldValue('setCurrency')==='USD'?'$':'€'}${price.toFixed(3)} / kWh`, gross, fees, net:gross-fees, split:fieldValue('setSplit') || 'Owner 90% · Operator 7% · Platform 3%', status:'Ready for invoice' };
        settlements.push(rec);
        document.getElementById('settlementRunsTable')?.insertAdjacentHTML('beforeend', settlementRow(rec));
        SettlementCenter.closeModal();
        SettlementCenter.openDetail(rec.id);
        FleetLayout.toast(`Settlement run ${rec.id} created`);
      },
      openDetail(id: string): void{
        const rec = settlements.find(x => x.id === id) || settlements[0];
        if (!rec) return;
        const drawer = ensurePanel('settlementDrawer','detail-drawer');
        const currency = rec.price.includes('$') ? 'USD' : 'EUR';
        drawer.innerHTML = `<button class="drawer-close" type="button" onclick="SettlementCenter.closeDrawer()">×</button><p class="eyebrow">Settlement Detail</p><h2>${rec.id}</h2><p class="muted">Traceable commercial layer between approved kWh, billing charges and payout/payment operations.</p><div class="info-grid"><div><span>Period</span><strong>${rec.period}</strong></div><div><span>Seller</span><strong>${rec.seller}</strong></div><div><span>Buyer</span><strong>${rec.buyer}</strong></div><div><span>Channel</span><strong>${rec.channel}</strong></div><div><span>Energy</span><strong>${rec.energy}</strong></div><div><span>Price</span><strong>${rec.price}</strong></div><div><span>Gross</span><strong>${money(rec.gross,currency)}</strong></div><div><span>Fees</span><strong>${money(rec.fees,currency)}</strong></div><div><span>Net</span><strong>${money(rec.net,currency)}</strong></div><div><span>Status</span><strong>${rec.status}</strong></div></div><div class="commercial-spaced-v120"><h3>Linked Objects</h3><div class="info-grid"><div><span>Accounting Records</span><strong>Energy Ledger ready</strong><small>Source kWh validated before settlement.</small></div><div><span>Billing Handoff</span><strong>Charge → Invoice Line</strong><small>Creates traceable invoice line.</small></div><div><span>Payouts</span><strong>${rec.split}</strong><small>Used by Payment Settings payout queue.</small></div><div><span>Audit</span><strong>Snapshot saved</strong><small>Price, fee and FX rule versioned.</small></div></div></div><div class="modal-actions"><button class="secondary-action" type="button" onclick="FleetLayout.toast('Billing charge draft created')">Create Billing Charge</button><button class="primary-action" type="button" onclick="FleetLayout.toast('Payout queue entry created')">Create Payout</button></div>`;
        drawer.classList.add('open');
      },
      createAgreement(): void{
        const modal = ensurePanel('settlementModal');
        modal.innerHTML = `<div class="modal-card"><button class="modal-close" type="button" onclick="SettlementCenter.closeModal()">×</button><div class="panel-head"><div><h2>Energy Sale Agreement</h2><p>Define who sells energy, who buys it, through which channel, at what price and where funds go.</p></div><span class="badge info">Draft Agreement</span></div><div class="client-form-grid two-col"><label>Agreement Code<input id="agrCode" value="ESA-004" /></label><label>Status<select id="agrStatus"><option>Draft</option><option>Review</option><option>Active</option></select></label><label>Seller<select id="agrSeller"><option>Arpi Solar Group</option><option>Green Valley Estate</option><option>Ivan Petrov</option></select></label><label>Buyer<input id="agrBuyer" value="New Energy Buyer LLC" /></label><label>Sales Channel<select id="agrChannel"><option>Grid</option><option>Trader</option><option>Aggregator</option><option>Direct PPA</option><option>Marketplace</option></select></label><label>Pricing Model<select id="agrPricing"><option>Fixed Price</option><option>Market Linked</option><option>TOU Price</option><option>Contract Override</option></select></label><label>Price per kWh<input id="agrPrice" value="€0.090 / kWh" /></label><label>Settlement Period<select id="agrPeriod"><option>Monthly</option><option>Quarterly</option><option>Annual</option><option>Custom PPA schedule</option></select></label><label>Payout Destination<input id="agrDestination" value="Ameriabank · EUR" /></label><label>Revenue Sharing<input id="agrSplit" value="Owner 90% · Operator 7% · Platform 3%" /></label></div><div class="modal-actions"><button class="secondary-action" type="button" onclick="SettlementCenter.closeModal()">Cancel</button><button class="primary-action" type="button" onclick="SettlementCenter.saveAgreement()">Save Agreement Draft</button></div></div>`;
        modal.classList.add('open');
      },
      saveAgreement(): void{
        const rec = { id:fieldValue('agrCode') || `ESA-${String(agreements.length+1).padStart(3,'0')}`, seller:fieldValue('agrSeller') || 'Arpi Solar Group', buyer:fieldValue('agrBuyer') || 'New Energy Buyer LLC', channel:fieldValue('agrChannel') || 'Aggregator', price:fieldValue('agrPrice') || '€0.090 / kWh', period:fieldValue('agrPeriod') || 'Monthly', destination:fieldValue('agrDestination') || 'Ameriabank · EUR', status:fieldValue('agrStatus') || 'Draft' };
        agreements.push(rec);
        document.getElementById('agreementsTable')?.insertAdjacentHTML('beforeend', agreementRow(rec));
        SettlementCenter.closeModal();
        FleetLayout.toast(`Energy sale agreement ${rec.id} saved`);
      },
      closeModal(): void{ closePanel('settlementModal'); },
      closeDrawer(): void{ closePanel('settlementDrawer'); }
    };

    FleetLayout.mount(`
      <section class="page-hero"><div><p class="eyebrow">Global Admin · Financial Operations</p><h1>Settlement Center</h1><p class="muted">Commercial settlement layer for exported energy, direct PPA, grid feed-in, aggregator pools, BESS dispatch, revenue sharing and payout readiness.</p></div><div class="toolbar"><button class="secondary-action" onclick="location.href='energy-accounting.html'">Energy Accounting</button><button class="primary-action" onclick="SettlementCenter.createRun()">Create Settlement Run</button></div></section>
      <section class="module-grid commercial-kpis-v78"><article class="kpi-card"><span>Settlement Runs</span><strong>${settlements.length}</strong><small>Current month</small></article><article class="kpi-card"><span>Gross Amount</span><strong>${money(totalGross)}</strong><small>Mixed-currency demo converted view</small></article><article class="kpi-card"><span>Net Amount</span><strong>${money(totalNet)}</strong><small>After platform / operator fees</small></article><article class="kpi-card"><span>Ready for Billing</span><strong>2</strong><small>Can generate invoice or payout</small></article></section>
      <section class="panel glass-card"><div class="panel-head"><div><h2>Settlement Flow</h2><p>Settlement converts approved Energy Ledger entries into payable / invoiceable commercial transactions.</p></div><span class="badge success">Aggregator-ready</span></div><div class="commercial-governance-flow-v99 settlement-flow-v160"><article><span>01</span><strong>Accounting Record</strong><small>Validated export / import / self-use kWh</small></article><article><span>02</span><strong>Sales Channel</strong><small>Grid, Trader, Aggregator, PPA, Marketplace</small></article><article><span>03</span><strong>Pricing Rule</strong><small>Fixed price, TOU, market price, contract override</small></article><article><span>04</span><strong>Revenue Split</strong><small>Owner, operator, platform, trader</small></article><article><span>05</span><strong>Invoice / Payout</strong><small>Billing and Payment Settings handoff</small></article></div></section>
      <section class="panel glass-card commercial-spaced-v120"><div class="panel-head"><div><h2>Settlement Runs</h2><p>Each settlement run is linked back to Energy Accounting and forward to Billing / Payment Settings.</p></div><button class="secondary-action" onclick="SettlementCenter.openDetail('SET-2026-06-001')">Open Detail</button></div><div class="data-table settlement-table-v160" id="settlementRunsTable"><div class="data-head settlement-row-v160"><span>Run</span><span>Seller / Buyer</span><span>Channel / Energy</span><span>Gross / Fees</span><span>Net / Split</span><span>Status</span></div>${rows}</div></section>
      <section class="panel glass-card commercial-spaced-v120"><div class="panel-head"><div><h2>Energy Sale Agreements</h2><p>Defines who sells energy, who buys it, through which channel, for what price and where funds go.</p></div><button class="secondary-action" onclick="SettlementCenter.createAgreement()">Create Agreement</button></div><div class="data-table settlement-agreement-table-v160" id="agreementsTable"><div class="data-head settlement-agreement-row-v160"><span>Agreement</span><span>Buyer / Channel</span><span>Price / Period</span><span>Payout Destination</span><span>Status</span></div>${agreementRows}</div></section>
      <section class="panel glass-card commercial-spaced-v120"><div class="panel-head"><div><h2>Settlement Controls</h2><p>These controls prevent Billing from using unsupported or unvalidated commercial energy data.</p></div></div><div class="info-grid"><div><span>Sales Channels</span><strong>Grid · Trader · Aggregator · Direct PPA · Marketplace · Self-use</strong><small>Each channel may use different pricing.</small></div><div><span>Settlement Statuses</span><strong>Draft · Calculated · Ready · Invoiced · Paid · Settled · Disputed</strong><small>Separate from invoice status.</small></div><div><span>Revenue Sharing</span><strong>Owner / Operator / Platform / Trader</strong><small>Needed for marketplace and aggregator payouts.</small></div><div><span>Billing Handoff</span><strong>Settlement → Charge → Invoice Line</strong><small>Billing receives a traceable settlement source.</small></div></div></section>
    `);

})();
