(() => {
interface StorageNormalizationField { field_key?: string; ui_label?: string; domain?: string; entity?: string; category?: string; description?: string; used_in?: string[]; unit?: string; normalization_rule?: string; data_type?: string; required_level?: string; }
interface StorageNormalizationState { tab: string; fields: StorageNormalizationField[]; }
const PATH_FIELDS = '../assets/data/Zentrid_UI_Field_Dictionary_v1.json';
    const state: StorageNormalizationState = { tab:'overview', fields:[] };
    function esc(v: unknown): string{const entities: Record<string, string>={'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'};return String(v??'').replace(/[&<>'"]/g,c=>entities[c]??c);}
    function badge(v: unknown): string{const s=String(v||'').toLowerCase();return `<span class="badge ${s.includes('required')?'success':s.includes('optional')?'neutral':'warning'}">${esc(v)}</span>`;}
    async function init(): Promise<void>{ const fd = await fetch(PATH_FIELDS,{cache:'no-store'}).then(r=>r.json()); state.fields = fd.fields || []; render(); }
    function storageFields(): StorageNormalizationField[]{ const terms=['battery','bms','storage','soc','soh','charge','discharge','ess','pcs','cycle']; return state.fields.filter(f=>{const hay=[f.field_key,f.ui_label,f.domain,f.entity,f.category,f.description,(f.used_in||[]).join(' ')].join(' ').toLowerCase();return terms.some(t=>hay.includes(t));}); }
    function byDomain(domain: string): StorageNormalizationField[]{ const hay=domain.toLowerCase(); return storageFields().filter(f=>[f.field_key,f.ui_label,f.domain,f.entity,f.description].join(' ').toLowerCase().includes(hay)); }
    function rowset(items: StorageNormalizationField[]): string{return items.slice(0,80).map(f=>`<div class="data-row storage-mapping-row-v94"><div><strong>${esc(f.ui_label)}</strong><small>${esc(f.field_key)}</small></div><div><strong>${esc((f.used_in||[]).join(' · ')||f.category)}</strong><small>${esc(f.entity||'Storage')}</small></div><div><strong>${esc(f.unit||'—')}</strong><small>Canonical unit</small></div><div><strong>${esc(f.normalization_rule||'Use normalized Zentrid value')}</strong><small>${esc(f.data_type||'value')}</small></div>${badge(f.required_level||'Optional')}<div class="row-actions"><button class="small-btn" onclick="ZentridLayout.toast('Field dictionary record: ${esc(f.field_key)}')">Open</button></div></div>`).join('');}
    function tabs(): string{return `<aside class="glass-card production-side-card-v92"><h3>Storage Workspace</h3>${[['overview','Overview'],['battery','Battery Fields'],['bms','BMS / ESS'],['power','Charge / Discharge'],['status','Status & Modes'],['validation','Validation Rules']].map(([id,label])=>`<button class="${state.tab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}</aside>`;}
    function overview(): string{const sf=storageFields();const units=[...new Set(sf.map(f=>f.unit).filter(Boolean))];return `<div class="section-title-v17"><div><h2>Storage Normalization Overview</h2><p class="muted">Storage fields are loaded from UI Dictionary. Labels and units are loaded from the UI Dictionary.</p></div></div><section class="kpi-grid compact-kpis"><article class="kpi-card green"><span>Storage Fields</span><strong>${sf.length}</strong><small>Battery · BMS · ESS · PCS</small></article><article class="kpi-card cyan"><span>Canonical Units</span><strong>${units.length}</strong><small>${esc(units.join(' · '))}</small></article><article class="kpi-card blue"><span>Temperature</span><strong>°C</strong><small>only normalized display unit</small></article><article class="kpi-card yellow"><span>Status Source</span><strong>Dictionary</strong><small>no vendor-only labels</small></article></section><div class="info-grid"><div><span>Entity label</span><strong>Device</strong></div><div><span>Storage labels</span><strong>Battery · BMS · ESS · PCS</strong></div><div><span>Power flow</span><strong>Charge / Discharge</strong></div><div><span>UI source</span><strong>UI Dictionary</strong></div></div>`;}
    function panel(title: string, desc: string, items: StorageNormalizationField[]): string{return `<div class="section-title-v17"><div><h2>${esc(title)}</h2><p class="muted">${esc(desc)}</p></div></div><div class="data-table storage-mapping-table-v94"><div class="data-head storage-mapping-row-v94"><span>UI Label</span><span>Used In</span><span>Unit</span><span>Normalization Rule</span><span>Level</span><span>Actions</span></div><div class="production-mapping-rows-v93">${rowset(items)}</div></div>`;}
    function validation(): string{return `<div class="section-title-v17"><div><h2>Validation Rules</h2><p class="muted">Storage values must use the same canonical rules everywhere in the UI.</p></div></div><div class="check-list unified-check-list"><label class="check-row done"><input type="checkbox" checked><span><b>SOC / SOH must be 0–100%</b><small>Normalize percentage values and flag impossible values.</small></span></label><label class="check-row done"><input type="checkbox" checked><span><b>Battery temperature uses °C</b><small>No non-canonical battery temperature labels in normalized UI.</small></span></label><label class="check-row done"><input type="checkbox" checked><span><b>Charge and discharge power use kW</b><small>W/MW source values must be converted before display.</small></span></label><label class="check-row done"><input type="checkbox" checked><span><b>Storage status is canonical</b><small>Vendor status text is preserved only as source detail, not as UI label.</small></span></label></div>`;}
    function active(): string{if(state.tab==='battery')return panel('Battery Fields','SOC, SOH, capacity, temperature, cycle and battery state fields.', byDomain('battery').concat(byDomain('soc')).concat(byDomain('soh'))); if(state.tab==='bms')return panel('BMS / ESS Fields','BMS communication, ESS state, pack and cell-level fields.', byDomain('bms').concat(byDomain('ess')).concat(byDomain('cell'))); if(state.tab==='power')return panel('Charge / Discharge Fields','Storage power flow fields and canonical units.', byDomain('charge').concat(byDomain('discharge'))); if(state.tab==='status')return panel('Status & Mode Fields','Normalized storage status, operating mode and control fields.', byDomain('mode').concat(byDomain('status'))); if(state.tab==='validation')return validation(); return overview();}
    function render(): void{ZentridLayout.mount(`<section class="page-hero production-hero"><div><p class="eyebrow">Global Admin · Data Governance</p><h1>Storage Normalization</h1><p class="muted">Canonical Battery / BMS / ESS / PCS field structure loaded from Zentrid normalization layer.</p></div><button class="freshness-card" onclick="ZentridLayout.toast('Storage normalization loaded')"><span class="pulse"></span><div><strong>Dictionary driven</strong><small>Battery Detail dictionary</small></div></button></section><section class="production-workspace-v92">${tabs()}<section class="glass-card production-main-card-v92">${active()}</section></section>`);document.querySelectorAll<HTMLElement>('[data-tab]').forEach((b: HTMLElement)=>{b.onclick=()=>{state.tab=b.dataset.tab || 'overview';render();};});}
    init();
})();
