(() => {
const tariffPlans = [
      {code:'industrial_operator_plus', name:'Industrial Operator Plus', currency:'EUR', customer:'Operator', billing:'Postpaid', base:'€500', stations:'3 included · €150 overage', devices:'Graduated device tiers', status:'Active'},
      {code:'enterprise_owner', name:'Enterprise Owner', currency:'EUR', customer:'End Customer', billing:'Prepaid', base:'€1,200', stations:'10 included · per MW option', devices:'Capacity-based', status:'Draft'},
      {code:'vendor_marketplace', name:'Vendor Marketplace', currency:'USD', customer:'Vendor', billing:'Postpaid', base:'$250', stations:'Not applicable', devices:'Vendor listing + commission', status:'Ready'}
    ];
    const rows = tariffPlans.map(p=>`<div class="data-row commercial-model-table-row-v126"><div><strong>${p.name}</strong><small>${p.code}</small></div><div><strong>${p.customer}</strong><small>${p.billing}</small></div><div><strong>${p.base}</strong><small>${p.currency}</small></div><div><strong>${p.stations}</strong><small>${p.devices}</small></div><span class="badge ${p.status==='Active'?'success':'warning'}">${p.status}</span></div>`).join('');
    ZentridLayout.mount(`<section class="page-hero"><div><p class="eyebrow">Global Admin · Financial Operations</p><h1>Tariff Management</h1><p class="muted">Tariff plans, pricing rules, device pricing, premium modules, SLA, discounts, taxes and simulator.</p></div><button class="secondary-action" onclick="location.href='commercial-models.html'">Back to Commercial Models</button></section><section class="module-grid commercial-kpis-v78"><article class="kpi-card"><span>Tariff Plans</span><strong>12</strong><small>8 active · 4 draft</small></article><article class="kpi-card"><span>Pricing Models</span><strong>6</strong><small>Flat, tiered, graduated, volume, capacity, revenue</small></article><article class="kpi-card"><span>Rule Priority</span><strong>5 levels</strong><small>Contract → defaults</small></article><article class="kpi-card"><span>Simulator</span><strong>Ready</strong><small>Pre-invoice calculation</small></article></section><section class="panel glass-card"><div class="panel-head"><div><h2>Tariff Plans</h2><p>This page will be expanded next with full tariff constructor and simulator.</p></div><button class="primary-action" onclick="ZentridLayout.toast('Tariff draft created in prototype')">Create Tariff</button></div><div class="data-table commercial-revenue-table-v126"><div class="data-head"><span>Tariff</span><span>Customer</span><span>Base</span><span>Rules</span><span>Status</span></div>${rows}</div></section>`);

})();
